import defineWorkflow from "/runtime/tools/workflow/defineWorkflow"

export default defineWorkflow({
  version: 1,
  id: "negrisk-flb-harvest-executor",
  name: "NegRisk Favourite-Longshot Bias Harvest Executor",
  description:
    "Consume the FLB scanner's longshot-tail short list and express each short as a maker BUY of the NO token (the only collateralised way to short an overpriced longshot YES on Polymarket's CLOB). Enforce diversification-first risk caps (per-event exposure cap, total exposure cap, max open positions) because tail losses realise only at event resolution and within-event names are mutually exclusive. Book EXPECTED edge (mark-to-model, central gamma) on fill, NOT realised P&L which only appears at resolution. Defaults to dryRun: true; submission lines are commented out.",
  triggers: [{ manual: true }],
  inputs: [
    { name: "signalKey", type: "string", required: false, default: "flb:eligible_baskets" },
    { name: "collateralPerNameUsd", type: "number", required: false, default: 25 },
    { name: "maxOpenPositions", type: "number", required: false, default: 8 },
    { name: "maxExposurePerEventUsd", type: "number", required: false, default: 50 },
    { name: "maxTotalExposureUsd", type: "number", required: false, default: 300 },
    { name: "maxDailyNotionalUsd", type: "number", required: false, default: 200 },
    { name: "maxDailyLossUsd", type: "number", required: false, default: 50 },
    { name: "makerLimitPriceOffsetBp", type: "number", required: false, default: 5 },
    { name: "minSellEdgeConservative", type: "number", required: false, default: 0.0 },
    { name: "dryRun", type: "boolean", required: false, default: true },
  ],
  output_mode: "inline",
  steps: [
    {
      id: "load_state",
      name: "Load open short positions, daily notional, total exposure at risk, and kill-switch state from KV",
      type: "ts",
      timeout: 15000,
      code: [
        'const todayDateStr = new Date().toISOString().slice(0, 10)',
        '',
        'const dailyPnlKey = "flb:daily_pnl:" + todayDateStr',
        'const dailyPnlRaw = await kv.get(dailyPnlKey)',
        'const dailyPnl = dailyPnlRaw ? (JSON.parse(dailyPnlRaw.value || dailyPnlRaw).realised_pnl_usd || 0) : 0',
        '',
        'const dailyNotionalKey = "flb:daily_notional:" + todayDateStr',
        'const dailyNotionalRaw = await kv.get(dailyNotionalKey)',
        'const dailyNotional = dailyNotionalRaw ? (JSON.parse(dailyNotionalRaw.value || dailyNotionalRaw).usd || 0) : 0',
        '',
        'const killRaw = await kv.get("flb:kill_switch_state")',
        'const killState = killRaw ? (JSON.parse(killRaw.value || killRaw).state || "armed") : "armed"',
        '',
        '// Sum exposure-at-risk across all OPEN short positions, grouped by event for the',
        '// per-event diversification cap. Exposure = collateral that goes to zero if the',
        '// shorted longshot resolves YES.',
        'const posRaw = await kv.list("flb:positions:")',
        'const openPositions = []',
        'let totalExposure = 0',
        'const exposureByEvent = {}',
        'const openTokens = {}',
        'for (const entry of (posRaw || [])) {',
        '  let p',
        '  try { p = JSON.parse(entry.value || "{}") } catch (e) { continue }',
        '  if (p.status !== "open" && p.status !== "dry_run_open") continue',
        '  const exp = Number(p.exposure_at_risk_usd || 0)',
        '  if (!Number.isFinite(exp)) continue',
        '  openPositions.push(p)',
        '  totalExposure += exp',
        '  exposureByEvent[p.event_slug] = (exposureByEvent[p.event_slug] || 0) + exp',
        '  if (p.no_token) openTokens[p.no_token] = true',
        '}',
        '',
        'const state = {',
        '  daily_realised_pnl_usd: dailyPnl,',
        '  daily_notional_used: dailyNotional,',
        '  kill_switch: killState,',
        '  open_positions_count: openPositions.length,',
        '  total_exposure_at_risk_usd: Number(totalExposure.toFixed(4)),',
        '  exposure_by_event: exposureByEvent,',
        '  open_tokens: openTokens,',
        '  timestamp: new Date().toISOString(),',
        '}',
        'await kv.set("flb:current_state", JSON.stringify(state))',
        '',
        'export default state',
      ].join("\n"),
    },
    {
      id: "evaluate_candidates",
      name: "Read the FLB short list, drop names already shorted, keep those clearing the conservative-edge floor",
      type: "ts",
      depends_on: ["load_state"],
      timeout: 15000,
      code: [
        'const signalKey = "flb:eligible_baskets"',
        'const minSellEdgeConservative = 0.0',
        '',
        'const sigRaw = await kv.get(signalKey)',
        'const sigParsed = sigRaw ? JSON.parse(sigRaw.value || sigRaw) : { short_candidates: [] }',
        'const candidates0 = Array.isArray(sigParsed.short_candidates) ? sigParsed.short_candidates : []',
        '',
        'const stateRaw = await kv.get("flb:current_state")',
        'const state = stateRaw ? JSON.parse(stateRaw.value || stateRaw) : { open_tokens: {} }',
        'const openTokens = state.open_tokens || {}',
        '',
        'const candidates = []',
        'for (const c of candidates0) {',
        '  if (!c.no_token || !c.yes_token) continue',
        '  if (openTokens[c.no_token]) continue',
        '  // Defensive re-check of the eligibility floor at consume time (the scanner already',
        '  // gated on it, but a stale KV payload could carry a sub-floor name). The conservative',
        '  // edge is the only venue-measurable component; require it strictly positive.',
        '  if (Number(c.sell_edge_conservative) <= minSellEdgeConservative) continue',
        '  if (!(Number(c.yes_price) > 0) || !(Number(c.yes_price) < 1)) continue',
        '  candidates.push(c)',
        '}',
        '// Highest conservative (measurable) edge first.',
        'candidates.sort((a, b) => Number(b.sell_edge_conservative) - Number(a.sell_edge_conservative))',
        '',
        'await kv.set("flb:last_candidates", JSON.stringify({ candidates, timestamp: new Date().toISOString() }))',
        'await fs.promises.writeFile("/workspace/scratch/flb_candidates.json", JSON.stringify({ candidates }, null, 2))',
        '',
        'export default {',
        '  totalShortCandidates: candidates0.length,',
        '  newCandidates: candidates.length,',
        '  top: candidates.slice(0, 5).map((c) => ({ slug: c.slug, yes_price: c.yes_price, sell_edge_conservative: c.sell_edge_conservative, sell_edge_central: c.sell_edge_central })),',
        '}',
      ].join("\n"),
    },
    {
      id: "risk_gate",
      name: "Apply diversification-first caps: per-event exposure, total exposure, max open positions, daily notional, kill-switch",
      type: "ts",
      depends_on: ["evaluate_candidates"],
      timeout: 10000,
      code: [
        'const collateralPerNameUsd = 25',
        'const maxOpenPositions = 8',
        'const maxExposurePerEventUsd = 50',
        'const maxTotalExposureUsd = 300',
        'const maxDailyNotionalUsd = 200',
        'const maxDailyLossUsd = 50',
        '',
        'const stateRaw = await kv.get("flb:current_state")',
        'const state = stateRaw ? JSON.parse(stateRaw.value || stateRaw) : {',
        '  daily_realised_pnl_usd: 0, daily_notional_used: 0, kill_switch: "armed",',
        '  open_positions_count: 0, total_exposure_at_risk_usd: 0, exposure_by_event: {},',
        '}',
        '',
        'const candRaw = await kv.get("flb:last_candidates")',
        'const candidates = (candRaw ? JSON.parse(candRaw.value || candRaw).candidates : []) || []',
        '',
        'const blocks = []',
        'const allowed = []',
        '',
        'if (state.kill_switch === "tripped") {',
        '  blocks.push({ reason: "kill_switch_tripped" })',
        '} else if (state.daily_realised_pnl_usd < -maxDailyLossUsd) {',
        '  await kv.set("flb:kill_switch_state", JSON.stringify({',
        '    state: "tripped", trippedAt: new Date().toISOString(),',
        '    reason: "daily_loss_cap_exceeded", daily_realised_pnl_usd: state.daily_realised_pnl_usd,',
        '  }))',
        '  blocks.push({ reason: "daily_loss_cap_exceeded", daily_realised_pnl_usd: state.daily_realised_pnl_usd })',
        '}',
        '',
        'if (blocks.length === 0) {',
        '  let remainingTotalExposure = Math.max(0, maxTotalExposureUsd - (state.total_exposure_at_risk_usd || 0))',
        '  let remainingDailyNotional = Math.max(0, maxDailyNotionalUsd - (state.daily_notional_used || 0))',
        '  let remainingSlots = Math.max(0, maxOpenPositions - (state.open_positions_count || 0))',
        '  // Mutable per-event exposure tracker seeded from current open exposure.',
        '  const evExposure = Object.assign({}, state.exposure_by_event || {})',
        '',
        '  if (remainingSlots <= 0) {',
        '    blocks.push({ reason: "max_open_positions_reached", count: state.open_positions_count })',
        '  } else if (remainingTotalExposure < 1) {',
        '    blocks.push({ reason: "total_exposure_cap_reached", used: state.total_exposure_at_risk_usd })',
        '  } else if (remainingDailyNotional < 1) {',
        '    blocks.push({ reason: "daily_notional_cap_reached", used: state.daily_notional_used })',
        '  } else {',
        '    for (const c of candidates) {',
        '      if (allowed.length >= remainingSlots) break',
        '      // Exposure for this short ~= the NO collateral we deploy (lost if the longshot wins).',
        '      // Use collateralPerNameUsd as the deployed amount; exposure is the full deployed sum.',
        '      const exposure = collateralPerNameUsd',
        '      if (exposure > remainingTotalExposure) continue',
        '      if (exposure > remainingDailyNotional) continue',
        '      const evUsed = evExposure[c.event_slug] || 0',
        '      // Per-event cap: within one negRisk event the shorted names are mutually exclusive,',
        '      // so concentration in a single event is a single correlated bet. Cap it hard.',
        '      if (evUsed + exposure > maxExposurePerEventUsd) {',
        '        blocks.push({ reason: "per_event_exposure_cap", event_slug: c.event_slug, used: evUsed })',
        '        continue',
        '      }',
        '      allowed.push({ ...c, deployed_collateral_usd: collateralPerNameUsd, exposure_at_risk_usd: exposure })',
        '      evExposure[c.event_slug] = evUsed + exposure',
        '      remainingTotalExposure -= exposure',
        '      remainingDailyNotional -= exposure',
        '    }',
        '  }',
        '}',
        '',
        'await kv.set("flb:risk_gate_result", JSON.stringify({ timestamp: new Date().toISOString(), allowed, blocks }))',
        '',
        'export default {',
        '  allowedCount: allowed.length,',
        '  blockCount: blocks.length,',
        '  blocks: blocks.slice(0, 5),',
        '  allowed_top: allowed.slice(0, 3).map((a) => ({ slug: a.slug, event_slug: a.event_slug, exposure_at_risk_usd: a.exposure_at_risk_usd })),',
        '}',
      ].join("\n"),
    },
    {
      id: "plan_and_short",
      name: "For each allowed name, refresh the NO orderbook and compute a maker BUY-NO limit; submit only when dryRun is false",
      type: "ts",
      depends_on: ["risk_gate"],
      timeout: 60000,
      allow: ["getPredictionOrderbook", "managePredictionOrders"],
      code: [
        '// Defense-in-depth: dryRun and the actual submission path are HARDCODED here. Live',
        '// promotion requires three traceable edits:',
        '//   1. set `const dryRun = false`',
        '//   2. uncomment the `managePredictionOrders` block below',
        '//   3. set collateralPerNameUsd to a small first-live value in the recipe',
        'const dryRun = true',
        'const makerLimitPriceOffsetBp = 5',
        'const offsetPrice = makerLimitPriceOffsetBp / 10000',
        '',
        'const gateRaw = await kv.get("flb:risk_gate_result")',
        'const gate = gateRaw ? JSON.parse(gateRaw.value || gateRaw) : { allowed: [] }',
        'const allowed = gate.allowed || []',
        '',
        'const intents = []',
        'const errors = []',
        '',
        '// Fetch the NO-token orderbook for each allowed name (we BUY NO to short the longshot YES).',
        'const obResults = await Promise.all(allowed.map(async (op) => {',
        '  try {',
        '    const ob = await callTool("getPredictionOrderbook", { tokenId: String(op.no_token), slippageSizes: [50] })',
        '    return { op, ob }',
        '  } catch (e) {',
        '    return { op, ob: null, error: String(e) }',
        '  }',
        '}))',
        '',
        'for (const { op, ob, error } of obResults) {',
        '  if (!ob) { errors.push({ slug: op.slug, reason: "orderbook_call_failed", error }); continue }',
        '  const summary = (ob && ob.summary) || {}',
        '  const bestBid = Number(summary.bestBid || 0)',
        '  const bestAsk = Number(summary.bestAsk || 0)',
        '  if (!Number.isFinite(bestBid) || !Number.isFinite(bestAsk) || bestBid <= 0 || bestAsk <= 0 || bestAsk <= bestBid) {',
        '    errors.push({ slug: op.slug, reason: "invalid_no_orderbook_state" })',
        '    continue',
        '  }',
        '',
        '  // Infer tick from the live NO price grid (Polymarket uses 0.01 or 0.001).',
        '  const levelPrices = [...(ob.bids || []), ...(ob.asks || [])].map((l) => Number(l.price)).filter((p) => p > 0).sort((a, b) => a - b)',
        '  let minGap = Infinity',
        '  for (let i = 1; i < levelPrices.length; i++) { const g = levelPrices[i] - levelPrices[i - 1]; if (g > 1e-9 && g < minGap) minGap = g }',
        '  const inferredTick = Number.isFinite(minGap) ? Math.round(minGap * 1000) / 1000 : 0.001',
        '  const tick = Math.max(0.001, Math.min(0.01, inferredTick || 0.001))',
        '  const roundToTick = (p) => Number((Math.round(p / tick) * tick).toFixed(6))',
        '',
        '  // Maker BUY-NO: improve the bid by the offset, but never cross the ask (maker-only).',
        '  // Clamp to [tick, bestAsk - tick] so the order rests and cannot take.',
        '  const maxBuy = roundToTick(bestAsk - tick)',
        '  let buyNoLimit = Math.min(roundToTick(bestBid + offsetPrice), maxBuy)',
        '  buyNoLimit = Math.max(tick, Math.min(1 - tick, buyNoLimit))',
        '  if (buyNoLimit >= bestAsk) buyNoLimit = roundToTick(bestBid)  // never cross',
        '  if (!(buyNoLimit > 0) || !(buyNoLimit < 1)) { errors.push({ slug: op.slug, reason: "degenerate_no_limit" }); continue }',
        '',
        '  // Shares bought = deployed collateral / NO price. Each share pays $1 if the longshot',
        '  // LOSES (NO resolves yes), 0 if the longshot WINS. Max loss = deployed collateral.',
        '  const shares = Number((op.deployed_collateral_usd / buyNoLimit).toFixed(4))',
        '  // EXPECTED edge (mark-to-model, central gamma): per-share NO edge = fair_no - price_no',
        '  //   fair_no = 1 - p_true_central ; price_no = buyNoLimit',
        '  //   = (1 - p_true_central) - buyNoLimit  (equals the YES sell-edge in YES space)',
        '  const fairNoCentral = 1 - Number(op.p_true_central)',
        '  const expectedEdgePerShare = fairNoCentral - buyNoLimit',
        '  const expectedEdgeUsd = Number((expectedEdgePerShare * shares).toFixed(4))',
        '',
        '  const intent = {',
        '    event_slug: op.event_slug,',
        '    slug: op.slug,',
        '    yes_token: op.yes_token,',
        '    no_token: op.no_token,',
        '    side: "buy",',
        '    outcome: "NO",',
        '    yes_price_at_plan: op.yes_price,',
        '    no_buy_limit: Number(buyNoLimit.toFixed(4)),',
        '    no_best_bid: bestBid,',
        '    no_best_ask: bestAsk,',
        '    deployed_collateral_usd: op.deployed_collateral_usd,',
        '    shares,',
        '    exposure_at_risk_usd: op.exposure_at_risk_usd,',
        '    expected_edge_usd_central: expectedEdgeUsd,',
        '    p_true_central: op.p_true_central,',
        '    status: dryRun ? "dry_run_open" : "open",',
        '    opened_at: new Date().toISOString(),',
        '    note: "Expected edge is a mark-to-model EV at central gamma; realised P&L only at event resolution.",',
        '  }',
        '',
        '  if (!dryRun) {',
        '    // PRODUCTION PATH — explicit operator authorization required.',
        '    try {',
        '      // const buyResult = await callTool("managePredictionOrders", {',
        '      //   action: "create",',
        '      //   tokenId: String(op.no_token),',
        '      //   side: "buy",',
        '      //   orderType: "limit",',
        '      //   price: intent.no_buy_limit,',
        '      //   sizeUsd: intent.deployed_collateral_usd,',
        '      // })',
        '      // intent.submission_id = buyResult.id',
        '      // intent.status = "open"',
        '      intent.status = "live_path_disabled_in_workflow"',
        '    } catch (e) {',
        '      intent.status = "submission_failed"',
        '      intent.error = String(e)',
        '    }',
        '  }',
        '',
        '  await kv.set("flb:positions:" + op.no_token, JSON.stringify(intent))',
        '  intents.push(intent)',
        '}',
        '',
        '// Track today notional (collateral) deployed.',
        'const todayKey = "flb:daily_notional:" + new Date().toISOString().slice(0, 10)',
        'const prevRaw = await kv.get(todayKey)',
        'const prev = prevRaw ? (JSON.parse(prevRaw.value || prevRaw).usd || 0) : 0',
        'const added = intents.reduce((s, q) => s + (q.deployed_collateral_usd || 0), 0)',
        'await kv.set(todayKey, JSON.stringify({ usd: prev + added, updated_at: new Date().toISOString() }))',
        '',
        'await fs.promises.writeFile("/workspace/scratch/flb_cycle.json", JSON.stringify({ intents, errors, dryRun }, null, 2))',
        '',
        'export default {',
        '  intentCount: intents.length,',
        '  errorCount: errors.length,',
        '  dryRun,',
        '  total_deployed_collateral_usd: Number(added.toFixed(2)),',
        '  total_expected_edge_usd_central: Number(intents.reduce((s, q) => s + (q.expected_edge_usd_central || 0), 0).toFixed(4)),',
        '}',
      ].join("\n"),
    },
    {
      id: "monitor_and_mark",
      name: "Re-check open shorts for hypothetical fills, mark expected edge, recompute total exposure, trip kill-switch on exposure or realised-loss breach",
      type: "ts",
      depends_on: ["plan_and_short"],
      timeout: 60000,
      allow: ["getPredictionOrderbook"],
      code: [
        'const dryRun = true',
        'const maxTotalExposureUsd = 300',
        '',
        'const posRaw = await kv.list("flb:positions:")',
        'const openEntries = []',
        'for (const entry of (posRaw || [])) {',
        '  let p',
        '  try { p = JSON.parse(entry.value || "{}") } catch (e) { continue }',
        '  if (p.status !== "open" && p.status !== "dry_run_open") continue',
        '  openEntries.push({ entry, p })',
        '}',
        '',
        'const obResults = await Promise.all(openEntries.map(async ({ entry, p }) => {',
        '  try {',
        '    const ob = await callTool("getPredictionOrderbook", { tokenId: String(p.no_token), slippageSizes: [50] })',
        '    return { entry, p, ob }',
        '  } catch (e) {',
        '    return { entry, p, ob: null }',
        '  }',
        '}))',
        '',
        'const marks = []',
        'for (const { entry, p, ob } of obResults) {',
        '  if (!ob) continue',
        '  const summary = (ob && ob.summary) || {}',
        '  const bestBid = Number(summary.bestBid || 0)',
        '  const bestAsk = Number(summary.bestAsk || 0)',
        '  // NaN guard (same lesson as Pack 2): a non-numeric book would propagate NaN into the',
        '  // exposure/kill-switch comparison and silently mask risk. Skip on invalid book.',
        '  if (!Number.isFinite(bestBid) || !Number.isFinite(bestAsk) || bestBid <= 0 || bestAsk <= 0 || bestAsk <= bestBid) continue',
        '',
        '  // Maker BUY-NO fills when a taker sells into our resting bid: bestAsk drops to <= our limit.',
        '  let filled = false',
        '  if (Number(p.no_buy_limit) > 0 && bestAsk <= Number(p.no_buy_limit)) filled = true',
        '',
        '  if (!filled) {',
        '    await kv.set(entry.key, JSON.stringify({ ...p, last_seen_no_mid: (bestBid + bestAsk) / 2, last_seen_at: new Date().toISOString() }))',
        '    continue',
        '  }',
        '',
        '  // On fill the short is OPEN until event resolution. We book the EXPECTED edge as an EV',
        '  // mark (already computed at plan time); realised P&L is deferred to resolution and is NOT',
        '  // added to realised daily P&L here. Exposure (deployed collateral) is now live.',
        '  const update = {',
        '    ...p,',
        '    status: dryRun ? "filled_dry_run" : "filled_live",',
        '    filled_at: new Date().toISOString(),',
        '    expected_edge_marked_usd_central: Number(p.expected_edge_usd_central || 0),',
        '  }',
        '  await kv.set(entry.key, JSON.stringify(update))',
        '  marks.push({ slug: p.slug, event_slug: p.event_slug, exposure_at_risk_usd: p.exposure_at_risk_usd, expected_edge_usd_central: update.expected_edge_marked_usd_central })',
        '}',
        '',
        '// Recompute total live exposure across all open/filled positions and trip the kill-switch',
        '// if it breaches the cap. Exposure (not realised P&L) is the primary risk control because',
        '// FLB losses only realise at resolution.',
        'const allPos = await kv.list("flb:positions:")',
        'let totalExposure = 0',
        'let totalExpectedEdge = 0',
        'for (const e of (allPos || [])) {',
        '  try {',
        '    const p = JSON.parse(e.value || "{}")',
        '    if (p.status === "open" || p.status === "dry_run_open" || p.status === "filled_dry_run" || p.status === "filled_live") {',
        '      const exp = Number(p.exposure_at_risk_usd || 0)',
        '      if (Number.isFinite(exp)) totalExposure += exp',
        '      const ed = Number(p.expected_edge_usd_central || 0)',
        '      if (Number.isFinite(ed)) totalExpectedEdge += ed',
        '    }',
        '  } catch (err) { /* skip */ }',
        '}',
        '',
        'let killAction = "none"',
        'if (totalExposure > maxTotalExposureUsd) {',
        '  await kv.set("flb:kill_switch_state", JSON.stringify({',
        '    state: "tripped", trippedAt: new Date().toISOString(),',
        '    reason: "total_exposure_cap_exceeded", total_exposure_at_risk_usd: Number(totalExposure.toFixed(4)),',
        '  }))',
        '  killAction = "tripped_on_exposure"',
        '}',
        '',
        'await kv.set("flb:exposure_state", JSON.stringify({',
        '  total_exposure_at_risk_usd: Number(totalExposure.toFixed(4)),',
        '  total_expected_edge_usd_central: Number(totalExpectedEdge.toFixed(4)),',
        '  computed_at: new Date().toISOString(),',
        '}))',
        '',
        'await fs.promises.writeFile("/workspace/scratch/flb_summary.md", [',
        '  "# FLB Harvest Executor — Cycle Summary",',
        '  "",',
        '  "Fills this cycle: " + marks.length,',
        '  "Total exposure at risk (USD): " + totalExposure.toFixed(2) + " / cap " + maxTotalExposureUsd,',
        '  "Total EXPECTED edge booked (USD, central gamma, mark-to-model NOT realised): " + totalExpectedEdge.toFixed(4),',
        '  "Kill-switch action: " + killAction,',
        '  "",',
        '  "NOTE: Expected edge is an EV mark. Realised P&L (incl. the fat tail when a shorted",',
        '  "longshot wins) only materialises at event resolution. Exposure is the primary control.",',
        '  ...marks.map((m) => "- " + m.slug + " | exposure $" + Number(m.exposure_at_risk_usd).toFixed(2) + " | exp.edge $" + Number(m.expected_edge_usd_central).toFixed(4)),',
        '].join("\\n"))',
        '',
        'export default {',
        '  fills_this_cycle: marks.length,',
        '  total_exposure_at_risk_usd: Number(totalExposure.toFixed(2)),',
        '  total_expected_edge_usd_central: Number(totalExpectedEdge.toFixed(4)),',
        '  kill_action: killAction,',
        '}',
      ].join("\n"),
    },
  ],
})
