import defineWorkflow from "/runtime/tools/workflow/defineWorkflow"

export default defineWorkflow({
  version: 1,
  id: "negrisk-maker-yield-scanner",
  name: "NegRisk Maker Yield Scanner",
  description:
    "Scan active Polymarket negRisk event constituents, depth-walk each for bid + ask sides, compute quoted-spread-based maker yield under three AS scenarios, and surface only constituents passing the principled mean-price + spread-fraction eligibility filter (mean_price >= 0.15 AND quote_half_spread_fraction <= 0.00375).",
  triggers: [{ manual: true }],
  inputs: [
    { name: "limit", type: "number", required: false, default: 500 },
    { name: "minMeanPrice", type: "number", required: false, default: 0.15 },
    { name: "maxSpreadFraction", type: "number", required: false, default: 0.00375 },
    { name: "minConstituents", type: "number", required: false, default: 3 },
    { name: "maxAbsDeviation", type: "number", required: false, default: 0.10 },
    { name: "minEventVolumeUsd", type: "number", required: false, default: 1000000 },
    { name: "makerRebateBp", type: "number", required: false, default: 18.75 },
    { name: "depthSizeUsd", type: "number", required: false, default: 50 },
    { name: "captureFraction", type: "number", required: false, default: 0.05 },
    { name: "maxConstituentsToWalk", type: "number", required: false, default: 100 },
    { name: "snapshotPrefix", type: "string", required: false, default: "makeryld:" },
  ],
  output_mode: "inline",
  steps: [
    {
      id: "fetch_and_register",
      name: "Fetch active Polymarket events and capture the auto-registered SQL table name",
      type: "ts",
      timeout: 60000,
      allow: ["fetchPolymarketData"],
      code: [
        '// Self-bootstrap pattern (mirrors Pack 1 surfacer Step 1).',
        '// `fetchPolymarketData({ dataset: "events" })` via callTool exceeds the ts-exec',
        '// response budget, but via exec to host-tools at limit=5 it completes in ~1.6s',
        '// and auto-registers fetchPolymarketData_<hash>.',
        'try {',
        '  await exec("mkdir -p /workspace/scratch && host-tools fetchPolymarketData \'{\\"dataset\\":\\"events\\",\\"active\\":true,\\"limit\\":5}\' --json-output-only > /workspace/scratch/makeryld_bootstrap.txt 2>&1")',
        '} catch (e) {',
        '  // sqlite_master discovery will fall back to any pre-existing table.',
        '}',
        '',
        'const tableQuery = await sql("SELECT name FROM sqlite_master WHERE type=\'table\' AND name LIKE \'fetchPolymarketData_%\' ORDER BY ROWID DESC LIMIT 1")',
        'const sourceTable = (tableQuery && tableQuery[0] && tableQuery[0].name) || null',
        '',
        'let tableName',
        'let rowCount = 0',
        'if (sourceTable) {',
        '  // Alias + dedup-by-market_id (host tool appends across calls within a session).',
        '  await exec("sql query \'DROP TABLE IF EXISTS polymarket_makeryld_raw\'")',
        '  await exec("sql query \'CREATE TABLE polymarket_makeryld_raw AS SELECT * FROM " + sourceTable + " WHERE rowid IN (SELECT MAX(rowid) FROM " + sourceTable + " GROUP BY market_id)\'")',
        '  const countResult = await sql("SELECT COUNT(*) AS n FROM polymarket_makeryld_raw")',
        '  rowCount = Number((countResult && countResult[0] && countResult[0].n) || 0)',
        '  tableName = "polymarket_makeryld_raw"',
        '} else {',
        '  tableName = "polymarket_makeryld_raw"',
        '  rowCount = 0',
        '}',
        '',
        'const fetchMeta = { table: tableName, fetched: rowCount, timestamp: new Date().toISOString() }',
        'await kv.set("makeryld:current_table", JSON.stringify(fetchMeta))',
        '',
        'export default fetchMeta',
      ].join("\n"),
    },
    {
      id: "walk_and_score",
      name: "Depth-walk every active negRisk constituent on both sides, compute quoted spread and three-scenario maker yield",
      type: "ts",
      depends_on: ["fetch_and_register"],
      timeout: 180000,
      allow: ["getPredictionOrderbook"],
      code: [
        'const minMeanPrice = 0.15',
        'const maxSpreadFraction = 0.00375',
        'const minConstituents = 3',
        'const maxAbsDeviation = 0.10',
        'const minEventVolumeUsd = 1000000',
        'const makerRebateBp = 18.75',
        'const depthSizeUsd = 50',
        'const captureFraction = 0.05',
        'const maxConstituentsToWalk = 100',
        '',
        'const tableMeta = await kv.get("makeryld:current_table")',
        'const tableMetaParsed = tableMeta ? JSON.parse(tableMeta.value || tableMeta) : null',
        'const tableName = (tableMetaParsed && tableMetaParsed.table) || "polymarket_makeryld_raw"',
        '',
        '// Filter to negRisk events at the structural floor: sum_yes near 1.0 + flagship volume.',
        '// We only score constituents of events that survive the structural filter to keep',
        '// scan cost proportional to plausibly-deployable opportunity.',
        'const eventAggSql =',
        '  "SELECT event_slug, MIN(event_title) AS event_title, COUNT(*) AS n, " +',
        '  "ROUND(SUM(CAST(yes_price AS REAL)), 6) AS sum_yes, " +',
        '  "ROUND(SUM(CAST(volume_total_usd AS REAL)), 0) AS ev_vol " +',
        '  "FROM " + tableName + " " +',
        '  "WHERE event_slug IS NOT NULL AND CAST(hours_until_end AS REAL) > 0 " +',
        '  "GROUP BY event_slug " +',
        '  "HAVING n >= " + minConstituents',
        'const eventRows = await sql(eventAggSql)',
        '',
        'const eligibleEvents = (eventRows || []).filter((r) => {',
        '  const sumYes = Number(r.sum_yes)',
        '  if (Math.abs(sumYes - 1.0) > maxAbsDeviation) return false',
        '  if (Number(r.ev_vol || 0) < minEventVolumeUsd) return false',
        '  return true',
        '})',
        '',
        '// Pull all constituents of eligible events in one SQL fetch + group in JS',
        '// (no per-event WHERE-clause concatenation; eliminates SQL injection vector).',
        'const allConstSql =',
        '  "SELECT event_slug, event_title, slug, question, " +',
        '  "CAST(yes_price AS REAL) AS yes_price, " +',
        '  "CAST(volume_24h_usd AS REAL) AS vol_24h, " +',
        '  "CAST(volume_total_usd AS REAL) AS vol_total, " +',
        '  "SUBSTR(clob_token_ids, 1, INSTR(clob_token_ids, \\",\\") - 1) AS yes_token " +',
        '  "FROM " + tableName + " " +',
        '  "WHERE CAST(hours_until_end AS REAL) > 0"',
        'const allConstituents = await sql(allConstSql)',
        '',
        'const eligibleEventSlugs = new Set(eligibleEvents.map((e) => e.event_slug))',
        'const constituentsToScore = (allConstituents || [])',
        '  .filter((c) => c.event_slug && eligibleEventSlugs.has(c.event_slug))',
        '  .filter((c) => c.yes_token)',
        '  .slice(0, maxConstituentsToWalk)',
        '',
        '// Parallel orderbook walks: Promise.all to avoid sequential timeout.',
        '// For Pack 2 we need BOTH bid and ask sides for the quoted-spread calculation,',
        '// so each constituent contributes one getPredictionOrderbook call (it returns both sides).',
        'const results = await Promise.all(constituentsToScore.map(async (c) => {',
        '  try {',
        '    const ob = await callTool("getPredictionOrderbook", {',
        '      tokenId: String(c.yes_token),',
        '      slippageSizes: [depthSizeUsd],',
        '    })',
        '    return { c, ob }',
        '  } catch (e) {',
        '    return { c, ob: null }',
        '  }',
        '}))',
        '',
        'const scored = []',
        'const rebateRate = makerRebateBp / 10000',
        '',
        'for (const { c, ob } of results) {',
        '  if (!ob) continue',
        '  const summary = (ob && ob.summary) || {}',
        '  const slip = (ob && ob.slippageEstimates) || []',
        '',
        '  const bestBid = Number(summary.bestBid || 0)',
        '  const bestAsk = Number(summary.bestAsk || 0)',
        '  const bidEst = slip.find((x) => x.size === depthSizeUsd && x.side === "sell")',
        '  const askEst = slip.find((x) => x.size === depthSizeUsd && x.side === "buy")',
        '',
        '  // Use avgFillPrice at $50 if available (more robust to TOB ephemera);',
        '  // fall back to best bid/ask if depth-walk values missing.',
        '  const avgBid = bidEst ? Number(bidEst.avgFillPrice) : bestBid',
        '  const avgAsk = askEst ? Number(askEst.avgFillPrice) : bestAsk',
        '',
        '  if (avgBid <= 0 || avgAsk <= 0 || avgAsk <= avgBid) continue',
        '',
        '  const midPrice = (avgBid + avgAsk) / 2',
        '  const quoteHalfSpread = (avgAsk - avgBid) / 2',
        '  const quoteHalfSpreadFraction = quoteHalfSpread / midPrice',
        '',
        '  // Daily notional flow estimate: prefer 24h volume; fall back to lifetime / 30d.',
        '  const dailyVolumeUsd = c.vol_24h && c.vol_24h > 0',
        '    ? Number(c.vol_24h)',
        '    : (Number(c.vol_total || 0) / 30)',
        '  const dailyCapturedNotional = dailyVolumeUsd * captureFraction',
        '',
        '  // Three AS scenarios from WORLD_CUP_MM.md / polymarket_mm_sim.py.',
        '  // Per-fill net = rebate_rate - scenario_fraction * spread_fraction.',
        '  // Scaled by daily captured notional gives per-day net.',
        '  const naiveNetPerDay = dailyCapturedNotional * (rebateRate - 0.0 * quoteHalfSpreadFraction)',
        '  const moderateNetPerDay = dailyCapturedNotional * (rebateRate - 0.5 * quoteHalfSpreadFraction)',
        '  const informedNetPerDay = dailyCapturedNotional * (rebateRate - 1.0 * quoteHalfSpreadFraction)',
        '',
        '  // Eligibility: principled filter (NOT post-hoc P&L selection).',
        '  // Also require nonzero volume so we do not surface markets with',
        '  // structurally-passing prices but zero expected fills — the executor',
        '  // would otherwise consume quote slots on dead books.',
        '  const meanPriceOk = midPrice >= minMeanPrice',
        '  const spreadOk = quoteHalfSpreadFraction <= maxSpreadFraction',
        '  const volumeOk = dailyVolumeUsd > 0',
        '  const eligible = meanPriceOk && spreadOk && volumeOk',
        '',
        '  scored.push({',
        '    event_slug: c.event_slug,',
        '    event_title: c.event_title,',
        '    slug: c.slug,',
        '    question: c.question,',
        '    yes_token: c.yes_token,',
        '    best_bid: bestBid,',
        '    best_ask: bestAsk,',
        '    avg_bid_50: avgBid,',
        '    avg_ask_50: avgAsk,',
        '    mid_price: Number(midPrice.toFixed(6)),',
        '    quote_half_spread: Number(quoteHalfSpread.toFixed(6)),',
        '    quote_half_spread_fraction: Number(quoteHalfSpreadFraction.toFixed(6)),',
        '    daily_volume_usd: Math.round(dailyVolumeUsd),',
        '    daily_captured_notional_usd: Math.round(dailyCapturedNotional),',
        '    naive_net_per_day_usd: Number(naiveNetPerDay.toFixed(4)),',
        '    moderate_net_per_day_usd: Number(moderateNetPerDay.toFixed(4)),',
        '    informed_net_per_day_usd: Number(informedNetPerDay.toFixed(4)),',
        '    mean_price_ok: meanPriceOk,',
        '    spread_ok: spreadOk,',
        '    volume_ok: volumeOk,',
        '    eligible,',
        '  })',
        '}',
        '',
        'scored.sort((a, b) => b.moderate_net_per_day_usd - a.moderate_net_per_day_usd)',
        '',
        'await fs.promises.writeFile(',
        '  "/workspace/scratch/makeryld_scored.json",',
        '  JSON.stringify(scored, null, 2)',
        ')',
        '',
        'export default {',
        '  scoredCount: scored.length,',
        '  eligibleCount: scored.filter((s) => s.eligible).length,',
        '  filtered_out_by_mean_price: scored.filter((s) => !s.mean_price_ok).length,',
        '  filtered_out_by_spread: scored.filter((s) => s.mean_price_ok && !s.spread_ok).length,',
        '  filtered_out_by_volume: scored.filter((s) => s.mean_price_ok && s.spread_ok && !s.volume_ok).length,',
        '  top_eligible: scored.filter((s) => s.eligible).slice(0, 10),',
        '}',
      ].join("\n"),
    },
    {
      id: "filter_and_surface",
      name: "Filter to eligible constituents and persist to KV for executor consumption",
      type: "ts",
      depends_on: ["walk_and_score"],
      timeout: 30000,
      code: [
        'const raw = await fs.promises',
        '  .readFile("/workspace/scratch/makeryld_scored.json", "utf8")',
        '  .catch(() => "[]")',
        'const scored = JSON.parse(raw)',
        '',
        'const eligible = scored.filter((s) => s.eligible)',
        '',
        '// Aggregate per-event basket totals for the eligible subset.',
        'const byEvent = {}',
        'for (const s of eligible) {',
        '  const slug = s.event_slug',
        '  if (!byEvent[slug]) {',
        '    byEvent[slug] = {',
        '      event_slug: slug,',
        '      event_title: s.event_title,',
        '      constituents: 0,',
        '      naive_net_per_day_usd: 0,',
        '      moderate_net_per_day_usd: 0,',
        '      informed_net_per_day_usd: 0,',
        '    }',
        '  }',
        '  byEvent[slug].constituents++',
        '  byEvent[slug].naive_net_per_day_usd += s.naive_net_per_day_usd',
        '  byEvent[slug].moderate_net_per_day_usd += s.moderate_net_per_day_usd',
        '  byEvent[slug].informed_net_per_day_usd += s.informed_net_per_day_usd',
        '}',
        '',
        'const eventBaskets = Object.values(byEvent).sort(',
        '  (a, b) => b.moderate_net_per_day_usd - a.moderate_net_per_day_usd',
        ')',
        '',
        'const timestamp = new Date().toISOString()',
        'const payload = {',
        '  timestamp,',
        '  eligible_constituents: eligible,',
        '  event_baskets: eventBaskets,',
        '  total_eligible: eligible.length,',
        '  total_naive_net_per_day_usd: eligible.reduce((s, x) => s + x.naive_net_per_day_usd, 0),',
        '  total_moderate_net_per_day_usd: eligible.reduce((s, x) => s + x.moderate_net_per_day_usd, 0),',
        '  total_informed_net_per_day_usd: eligible.reduce((s, x) => s + x.informed_net_per_day_usd, 0),',
        '}',
        '',
        'await kv.set("makeryld:eligible_constituents", JSON.stringify(payload))',
        'const hourKey = "makeryld:" + timestamp.slice(0, 13)',
        'await kv.set(hourKey, JSON.stringify(payload))',
        '',
        'await fs.promises.writeFile(',
        '  "/workspace/scratch/makeryld_eligible.json",',
        '  JSON.stringify(payload, null, 2)',
        ')',
        '',
        'const lines = []',
        'lines.push("# NegRisk Maker Yield — Eligibility Scan")',
        'lines.push("")',
        'lines.push("Timestamp: " + timestamp)',
        'lines.push("Eligible constituents: " + eligible.length)',
        'lines.push("Total moderate-AS net per day (USD): " + payload.total_moderate_net_per_day_usd.toFixed(2))',
        'lines.push("")',
        'if (eventBaskets.length > 0) {',
        '  lines.push("## Per-event baskets (moderate AS)")',
        '  for (const b of eventBaskets) {',
        '    lines.push(',
        '      "- **" + b.event_slug + "** (" + b.constituents + " eligible) | " +',
        '      "naive $" + b.naive_net_per_day_usd.toFixed(2) + "/d | " +',
        '      "moderate $" + b.moderate_net_per_day_usd.toFixed(2) + "/d | " +',
        '      "informed $" + b.informed_net_per_day_usd.toFixed(2) + "/d"',
        '    )',
        '  }',
        '}',
        'if (eligible.length > 0) {',
        '  lines.push("")',
        '  lines.push("## Top eligible constituents (by moderate-AS net per day)")',
        '  for (const s of eligible.slice(0, 10)) {',
        '    lines.push(',
        '      "- " + s.slug + " | mid $" + s.mid_price.toFixed(3) + " | " +',
        '      "spread frac " + (s.quote_half_spread_fraction * 100).toFixed(3) + "% | " +',
        '      "24h vol $" + s.daily_volume_usd.toLocaleString() + " | " +',
        '      "mod $" + s.moderate_net_per_day_usd.toFixed(2) + "/d"',
        '    )',
        '  }',
        '}',
        'await fs.promises.writeFile("/workspace/scratch/makeryld_eligibility.md", lines.join("\\n"))',
        '',
        'export default {',
        '  total_eligible: eligible.length,',
        '  total_event_baskets: eventBaskets.length,',
        '  total_moderate_net_per_day_usd: Number(payload.total_moderate_net_per_day_usd.toFixed(2)),',
        '  top_event_baskets: eventBaskets.slice(0, 3),',
        '}',
      ].join("\n"),
    },
  ],
})
