import defineWorkflow from "/runtime/tools/workflow/defineWorkflow"

export default defineWorkflow({
  version: 1,
  id: "negrisk-maker-yield-executor",
  name: "NegRisk Maker Yield Executor",
  description:
    "Consume eligibility list from the maker-yield scanner KV, plan per-constituent two-sided maker limit-order intents at bestBid + 5bp (buy side) and bestAsk - 5bp (sell side), tick-rounded and maker-only, under risk caps, optionally submit when dryRun is false, and settle estimated P&L per cycle. Defaults to dryRun: true.",
  triggers: [{ manual: true }],
  inputs: [
    { name: "signalKey", type: "string", required: false, default: "makeryld:eligible_constituents" },
    { name: "notionalPerQuoteUsd", type: "number", required: false, default: 50 },
    { name: "maxOpenQuotes", type: "number", required: false, default: 5 },
    { name: "maxDailyNotionalUsd", type: "number", required: false, default: 2000 },
    { name: "maxDailyLossUsd", type: "number", required: false, default: 50 },
    { name: "makerLimitPriceOffsetBp", type: "number", required: false, default: 5 },
    { name: "makerRebateBp", type: "number", required: false, default: 18.75 },
    { name: "asScenarioFraction", type: "number", required: false, default: 0.5 },
    { name: "dryRun", type: "boolean", required: false, default: true },
  ],
  output_mode: "inline",
  steps: [
    {
      id: "load_state",
      name: "Load current open quotes, daily P&L, daily notional used, and kill-switch state from KV",
      type: "ts",
      timeout: 15000,
      code: [
        'const todayDateStr = new Date().toISOString().slice(0, 10)',
        '',
        'const dailyPnlKey = "makeryld:daily_pnl:" + todayDateStr',
        'const dailyPnlRaw = await kv.get(dailyPnlKey)',
        'const dailyPnl = dailyPnlRaw ? (JSON.parse(dailyPnlRaw.value || dailyPnlRaw).pnl_usd_gross || 0) : 0',
        '',
        'const dailyNotionalKey = "makeryld:daily_notional:" + todayDateStr',
        'const dailyNotionalRaw = await kv.get(dailyNotionalKey)',
        'const dailyNotional = dailyNotionalRaw ? (JSON.parse(dailyNotionalRaw.value || dailyNotionalRaw).usd || 0) : 0',
        '',
        'const killRaw = await kv.get("makeryld:kill_switch_state")',
        'const killState = killRaw ? (JSON.parse(killRaw.value || killRaw).state || "armed") : "armed"',
        '',
        'const quotesRaw = await kv.list("makeryld:quotes:")',
        'const openQuotes = []',
        'for (const entry of (quotesRaw || [])) {',
        '  try {',
        '    const q = JSON.parse(entry.value || "{}")',
        '    if (q.status === "open" || q.status === "dry_run_open") openQuotes.push(q)',
        '  } catch (e) { /* skip corrupted */ }',
        '}',
        '',
        'const state = {',
        '  daily_pnl_usd: dailyPnl,',
        '  daily_notional_used: dailyNotional,',
        '  kill_switch: killState,',
        '  open_quotes_count: openQuotes.length,',
        '  open_quotes: openQuotes,',
        '  timestamp: new Date().toISOString(),',
        '}',
        'await kv.set("makeryld:current_state", JSON.stringify(state))',
        '',
        'export default state',
      ].join("\n"),
    },
    {
      id: "evaluate_eligibility",
      name: "Read eligibility KV, identify constituents not already quoting",
      type: "ts",
      depends_on: ["load_state"],
      timeout: 15000,
      code: [
        'const signalKey = "makeryld:eligible_constituents"',
        '',
        'const sigRaw = await kv.get(signalKey)',
        'const sigParsed = sigRaw ? JSON.parse(sigRaw.value || sigRaw) : { eligible_constituents: [] }',
        'const eligible = Array.isArray(sigParsed.eligible_constituents) ? sigParsed.eligible_constituents : []',
        '',
        'const stateRaw = await kv.get("makeryld:current_state")',
        'const state = stateRaw ? JSON.parse(stateRaw.value || stateRaw) : { open_quotes: [] }',
        'const quotedTokens = new Set((state.open_quotes || []).map((q) => q.yes_token))',
        '',
        'const candidates = []',
        'for (const c of eligible) {',
        '  if (!c.yes_token) continue',
        '  if (quotedTokens.has(c.yes_token)) continue',
        '  if (c.mid_price <= 0.001 || c.mid_price >= 0.999) continue',
        '  candidates.push(c)',
        '}',
        '// Sort by descending moderate-AS net per day so the risk gate fills',
        '// the highest-expected-yield quotes first within the cap.',
        'candidates.sort((a, b) => (b.moderate_net_per_day_usd || 0) - (a.moderate_net_per_day_usd || 0))',
        '',
        '// Persist candidates for risk_gate to consume (KV is primary; file is mirror).',
        'const candidatesPayload = { candidates, timestamp: new Date().toISOString() }',
        'await kv.set("makeryld:last_candidates", JSON.stringify(candidatesPayload))',
        'await fs.promises.writeFile(',
        '  "/workspace/scratch/makeryld_candidates.json",',
        '  JSON.stringify(candidatesPayload, null, 2)',
        ')',
        '',
        'export default {',
        '  eligibleCount: eligible.length,',
        '  newCandidates: candidates.length,',
        '  topCandidates: candidates.slice(0, 5).map((c) => ({',
        '    slug: c.slug,',
        '    mid_price: c.mid_price,',
        '    spread_fraction: c.quote_half_spread_fraction,',
        '    moderate_net_per_day_usd: c.moderate_net_per_day_usd,',
        '  })),',
        '}',
      ].join("\n"),
    },
    {
      id: "risk_gate",
      name: "Apply daily-notional, max-open-quote, daily-loss, and kill-switch caps to candidates",
      type: "ts",
      depends_on: ["evaluate_eligibility"],
      timeout: 10000,
      code: [
        'const notionalPerQuoteUsd = 50',
        'const maxOpenQuotes = 5',
        'const maxDailyNotionalUsd = 2000',
        'const maxDailyLossUsd = 50',
        '',
        'const stateRaw = await kv.get("makeryld:current_state")',
        'const state = stateRaw ? JSON.parse(stateRaw.value || stateRaw) : {',
        '  daily_pnl_usd: 0,',
        '  daily_notional_used: 0,',
        '  kill_switch: "armed",',
        '  open_quotes_count: 0,',
        '}',
        '',
        'const candidatesRaw = await kv.get("makeryld:last_candidates")',
        'const candidatesPayload = candidatesRaw ? JSON.parse(candidatesRaw.value || candidatesRaw) : { candidates: [] }',
        'const candidates = candidatesPayload.candidates || []',
        '',
        'const blocks = []',
        'const allowed = []',
        '',
        'if (state.kill_switch === "tripped") {',
        '  blocks.push({ reason: "kill_switch_tripped" })',
        '} else if (state.daily_pnl_usd < -maxDailyLossUsd) {',
        '  await kv.set("makeryld:kill_switch_state", JSON.stringify({',
        '    state: "tripped",',
        '    trippedAt: new Date().toISOString(),',
        '    reason: "daily_loss_cap_exceeded",',
        '    daily_pnl_usd: state.daily_pnl_usd,',
        '  }))',
        '  blocks.push({ reason: "daily_loss_cap_exceeded", daily_pnl_usd: state.daily_pnl_usd })',
        '}',
        '',
        'if (blocks.length === 0) {',
        '  const remainingDailyNotional = Math.max(0, maxDailyNotionalUsd - state.daily_notional_used)',
        '  const remainingQuoteSlots = Math.max(0, maxOpenQuotes - (state.open_quotes_count || 0))',
        '',
        '  if (remainingQuoteSlots <= 0) {',
        '    blocks.push({ reason: "max_open_quotes_reached", count: state.open_quotes_count })',
        '  } else if (remainingDailyNotional < notionalPerQuoteUsd) {',
        '    blocks.push({ reason: "remaining_daily_notional_below_per_quote", remaining: remainingDailyNotional })',
        '  } else {',
        '    let remainingBudget = remainingDailyNotional',
        '    for (const c of candidates) {',
        '      if (allowed.length >= remainingQuoteSlots) break',
        '      if (remainingBudget < notionalPerQuoteUsd) break',
        '      allowed.push({ ...c, allocated_usd: notionalPerQuoteUsd })',
        '      remainingBudget -= notionalPerQuoteUsd',
        '    }',
        '  }',
        '}',
        '',
        'await kv.set("makeryld:risk_gate_result", JSON.stringify({',
        '  timestamp: new Date().toISOString(),',
        '  allowed,',
        '  blocks,',
        '}))',
        '',
        'export default {',
        '  allowedCount: allowed.length,',
        '  blockCount: blocks.length,',
        '  blocks,',
        '  allowed_top: allowed.slice(0, 3).map((a) => ({',
        '    slug: a.slug,',
        '    allocated_usd: a.allocated_usd,',
        '    moderate_net_per_day_usd: a.moderate_net_per_day_usd,',
        '  })),',
        '}',
      ].join("\n"),
    },
    {
      id: "plan_and_quote",
      name: "Compute per-constituent maker limit-price intents and submit them when dryRun is false",
      type: "ts",
      depends_on: ["risk_gate"],
      timeout: 60000,
      allow: ["getPredictionOrderbook", "managePredictionOrders"],
      code: [
        '// Defense-in-depth: dryRun, makerLimitPriceOffsetBp, and the actual submission',
        '// path are HARDCODED here. Recipe inputs for these are documented but require',
        '// explicit edits to this file to take effect. Live promotion requires three',
        '// traceable changes:',
        '//   1. set `const dryRun = false`',
        '//   2. uncomment the `managePredictionOrders` block below',
        '//   3. set notionalPerQuoteUsd to a small first-live value in the recipe',
        'const dryRun = true',
        'const makerLimitPriceOffsetBp = 5',
        'const offsetPrice = makerLimitPriceOffsetBp / 10000',
        '',
        'const gateRaw = await kv.get("makeryld:risk_gate_result")',
        'const gate = gateRaw ? JSON.parse(gateRaw.value || gateRaw) : { allowed: [] }',
        'const allowed = gate.allowed || []',
        '',
        'const quotes = []',
        'const errors = []',
        '',
        '// Parallel orderbook refresh across allowed constituents to keep step latency low.',
        'const obResults = await Promise.all(allowed.map(async (op) => {',
        '  try {',
        '    const ob = await callTool("getPredictionOrderbook", {',
        '      tokenId: String(op.yes_token),',
        '      slippageSizes: [50],',
        '    })',
        '    return { op, ob }',
        '  } catch (e) {',
        '    return { op, ob: null, error: String(e) }',
        '  }',
        '}))',
        '',
        'for (const { op, ob, error } of obResults) {',
        '  if (!ob) {',
        '    errors.push({ slug: op.slug, reason: "orderbook_call_failed", error })',
        '    continue',
        '  }',
        '  const summary = (ob && ob.summary) || {}',
        '  const bestBid = Number(summary.bestBid || 0)',
        '  const bestAsk = Number(summary.bestAsk || 0)',
        '',
        '  if (bestBid <= 0 || bestAsk <= 0 || bestAsk <= bestBid) {',
        '    errors.push({ slug: op.slug, reason: "invalid_orderbook_state" })',
        '    continue',
        '  }',
        '',
        '  // Infer the market tick from the live orderbook price grid (Polymarket uses',
        '  // 0.01 or 0.001). Fall back to 0.001 (the finest tick) if levels are sparse.',
        '  const levelPrices = [...(ob.bids || []), ...(ob.asks || [])]',
        '    .map((l) => Number(l.price))',
        '    .filter((p) => p > 0)',
        '    .sort((a, b) => a - b)',
        '  let minGap = Infinity',
        '  for (let i = 1; i < levelPrices.length; i++) {',
        '    const g = levelPrices[i] - levelPrices[i - 1]',
        '    if (g > 1e-9 && g < minGap) minGap = g',
        '  }',
        '  const inferredTick = Number.isFinite(minGap) ? Math.round(minGap * 1000) / 1000 : 0.001',
        '  const tick = Math.max(0.001, Math.min(0.01, inferredTick || 0.001))',
        '  const roundToTick = (p) => Number((Math.round(p / tick) * tick).toFixed(6))',
        '',
        '  // Two-sided maker quote: improve the bid (buy just ABOVE bestBid) and improve the',
        '  // ask (sell just BELOW bestAsk) by makerLimitPriceOffsetBp, then snap to the tick',
        '  // grid. Prior revisions used buy=bestAsk-offset / sell=bestBid+offset, which both',
        '  // (a) produced sub-tick prices the venue cannot accept and (b) inverted the sides',
        '  // on any book wider than one tick (buyLimit > sellLimit = self-crossed quotes).',
        '  // The 1-tick World Cup book masked both by collapsing each side to the mid.',
        '  // Maker-only clamps guarantee buy <= bestAsk - tick and sell >= bestBid + tick, so',
        '  // neither order can cross and the two sides can never collapse to one price.',
        '  const maxBuy = roundToTick(bestAsk - tick)',
        '  const minSell = roundToTick(bestBid + tick)',
        '  let buyLimit = Math.min(roundToTick(bestBid + offsetPrice), maxBuy)',
        '  let sellLimit = Math.max(roundToTick(bestAsk - offsetPrice), minSell)',
        '  buyLimit = Math.max(tick, Math.min(1 - tick, buyLimit))',
        '  sellLimit = Math.max(tick, Math.min(1 - tick, sellLimit))',
        '  // Narrow-spread guard: when the spread is <= 2 ticks the single inside tick can',
        '  // pull both improved prices onto the same mid tick (float rounding of a half-tick',
        '  // offset). Retreat both sides to the touch (join bestBid / bestAsk) — always valid,',
        '  // always maker, and strictly buy < sell since the book is at least one tick wide.',
        '  if (buyLimit >= sellLimit) {',
        '    buyLimit = roundToTick(bestBid)',
        '    sellLimit = roundToTick(bestAsk)',
        '  }',
        '  const sizePerSideUsd = (op.allocated_usd || 0) / 2',
        '',
        '  const buyOrder = {',
        '    side: "buy",',
        '    limit_price: Number(buyLimit.toFixed(4)),',
        '    size_usd: Number(sizePerSideUsd.toFixed(2)),',
        '    expected_shares: Number((sizePerSideUsd / buyLimit).toFixed(2)),',
        '  }',
        '  const sellOrder = {',
        '    side: "sell",',
        '    limit_price: Number(sellLimit.toFixed(4)),',
        '    size_usd: Number(sizePerSideUsd.toFixed(2)),',
        '    expected_shares: Number((sizePerSideUsd / sellLimit).toFixed(2)),',
        '  }',
        '',
        '  const quoteRecord = {',
        '    yes_token: op.yes_token,',
        '    slug: op.slug,',
        '    event_slug: op.event_slug,',
        '    quote_mid_at_post: (bestBid + bestAsk) / 2,',
        '    quote_half_spread_at_post: (bestAsk - bestBid) / 2,',
        '    moderate_net_per_day_usd: op.moderate_net_per_day_usd,',
        '    allocated_usd: op.allocated_usd,',
        '    orders: [buyOrder, sellOrder],',
        '    status: dryRun ? "dry_run_open" : "open",',
        '    opened_at: new Date().toISOString(),',
        '  }',
        '',
        '  if (!dryRun) {',
        '    // PRODUCTION PATH — explicit operator authorization required.',
        '    // The actual submission would call managePredictionOrders per side.',
        '    try {',
        '      // const buyResult = await callTool("managePredictionOrders", {',
        '      //   action: "create",',
        '      //   tokenId: String(op.yes_token),',
        '      //   side: "buy",',
        '      //   orderType: "limit",',
        '      //   price: buyOrder.limit_price,',
        '      //   sizeUsd: buyOrder.size_usd,',
        '      // })',
        '      // const sellResult = await callTool("managePredictionOrders", { ... })',
        '      // quoteRecord.orders[0].submission_id = buyResult.id',
        '      // quoteRecord.orders[1].submission_id = sellResult.id',
        '      // quoteRecord.status = "open"',
        '      quoteRecord.status = "live_path_disabled_in_workflow"',
        '    } catch (e) {',
        '      quoteRecord.status = "submission_failed"',
        '      quoteRecord.error = String(e)',
        '    }',
        '  }',
        '',
        '  await kv.set("makeryld:quotes:" + op.yes_token, JSON.stringify(quoteRecord))',
        '  quotes.push(quoteRecord)',
        '}',
        '',
        '// Track today\'s notional opened',
        'const todayKey = "makeryld:daily_notional:" + new Date().toISOString().slice(0, 10)',
        'const todayNotionalRaw = await kv.get(todayKey)',
        'const prevNotional = todayNotionalRaw ? (JSON.parse(todayNotionalRaw.value || todayNotionalRaw).usd || 0) : 0',
        'const newNotional = prevNotional + quotes.reduce((s, q) => s + (q.allocated_usd || 0), 0)',
        'await kv.set(todayKey, JSON.stringify({ usd: newNotional, updated_at: new Date().toISOString() }))',
        '',
        'await fs.promises.writeFile(',
        '  "/workspace/scratch/makeryld_cycle.json",',
        '  JSON.stringify({ quotes, errors, dryRun }, null, 2)',
        ')',
        '',
        'export default {',
        '  quoteCount: quotes.length,',
        '  errorCount: errors.length,',
        '  dryRun,',
        '  totalAllocatedUsd: quotes.reduce((s, q) => s + (q.allocated_usd || 0), 0),',
        '}',
      ].join("\n"),
    },
    {
      id: "monitor_and_settle",
      name: "Re-check open quotes for hypothetical fills (orderbook crossed our limits) and accrue estimated rebate net of AS",
      type: "ts",
      depends_on: ["plan_and_quote"],
      timeout: 60000,
      allow: ["getPredictionOrderbook", "managePredictionOrders"],
      code: [
        'const dryRun = true',
        'const makerRebateBp = 18.75',
        'const asScenarioFraction = 0.5  // moderate AS for default settlement',
        'const rebateRate = makerRebateBp / 10000',
        '',
        'const quotesRaw = await kv.list("makeryld:quotes:")',
        'const settlements = []',
        '',
        '// Refresh orderbooks in parallel for all open quotes.',
        'const openEntries = []',
        'for (const entry of (quotesRaw || [])) {',
        '  let q',
        '  try { q = JSON.parse(entry.value || "{}") } catch (e) { continue }',
        '  if (q.status !== "open" && q.status !== "dry_run_open") continue',
        '  openEntries.push({ entry, q })',
        '}',
        '',
        'const obResults = await Promise.all(openEntries.map(async ({ entry, q }) => {',
        '  try {',
        '    const ob = await callTool("getPredictionOrderbook", {',
        '      tokenId: String(q.yes_token),',
        '      slippageSizes: [50],',
        '    })',
        '    return { entry, q, ob }',
        '  } catch (e) {',
        '    return { entry, q, ob: null }',
        '  }',
        '}))',
        '',
        'for (const { entry, q, ob } of obResults) {',
        '  if (!ob) continue',
        '  const summary = (ob && ob.summary) || {}',
        '  const bestBid = Number(summary.bestBid || 0)',
        '  const bestAsk = Number(summary.bestAsk || 0)',
        '  // NaN guard: a non-numeric orderbook summary would propagate NaN through the AS',
        '  // calculation -> NaN persists to daily_pnl -> kill-switch comparison NaN < -cap is',
        '  // false, silently masking losses. Skip the entire quote update on invalid book.',
        '  if (!Number.isFinite(bestBid) || !Number.isFinite(bestAsk) || bestBid <= 0 || bestAsk <= 0 || bestAsk <= bestBid) {',
        '    continue',
        '  }',
        '  const currentMid = (bestBid + bestAsk) / 2',
        '  const currentHalfSpread = (bestAsk - bestBid) / 2',
        '',
        '  // Estimated fill: if the current orderbook has crossed past our limit,',
        '  // assume the limit got filled at our posted price.',
        '  let filled = []',
        '  for (const order of (q.orders || [])) {',
        '    if (order.side === "buy" && bestAsk <= order.limit_price) {',
        '      filled.push({ side: "buy", price: order.limit_price, size_usd: order.size_usd })',
        '    } else if (order.side === "sell" && bestBid >= order.limit_price) {',
        '      filled.push({ side: "sell", price: order.limit_price, size_usd: order.size_usd })',
        '    }',
        '  }',
        '',
        '  if (filled.length === 0) {',
        '    // Quote unchanged; persist updated mark only.',
        '    await kv.set(entry.key, JSON.stringify({',
        '      ...q,',
        '      last_seen_mid: currentMid,',
        '      last_seen_half_spread: currentHalfSpread,',
        '      last_seen_at: new Date().toISOString(),',
        '    }))',
        '    continue',
        '  }',
        '',
        '  // Estimated P&L per filled order: rebate − AS estimate (moderate scenario for default).',
        '  // AS cost semantics: maker incurs cost when the post-fill mid moves AGAINST the maker.',
        '  //   buy fill at f.price: loss when currentMid < f.price (price dropped after buying)',
        '  //   sell fill at f.price: loss when currentMid > f.price (price rose after selling)',
        '  // Capped at current half_spread × scenario_fraction so a noisy mid-move cannot dominate.',
        '  let cycleRebateUsd = 0',
        '  let cycleAsUsd = 0',
        '  for (const f of filled) {',
        '    const rebate = f.size_usd * rebateRate',
        '    let driftCost',
        '    if (f.side === "buy") {',
        '      driftCost = Math.max(0, f.price - currentMid) * f.size_usd / f.price',
        '    } else {',
        '      driftCost = Math.max(0, currentMid - f.price) * f.size_usd / f.price',
        '    }',
        '    const asCostCap = f.size_usd * currentHalfSpread / currentMid * asScenarioFraction',
        '    const asCost = Math.min(driftCost, asCostCap)',
        '    cycleRebateUsd += rebate',
        '    cycleAsUsd += asCost',
        '  }',
        '  const cycleNetUsd = cycleRebateUsd - cycleAsUsd',
        '',
        '  const update = {',
        '    ...q,',
        '    status: dryRun ? "filled_dry_run" : "filled_live",',
        '    filled_orders: filled,',
        '    last_seen_mid: currentMid,',
        '    last_seen_half_spread: currentHalfSpread,',
        '    cycle_rebate_usd: Number(cycleRebateUsd.toFixed(4)),',
        '    cycle_as_usd_gross_estimate: Number(cycleAsUsd.toFixed(4)),',
        '    cycle_net_usd_gross: Number(cycleNetUsd.toFixed(4)),',
        '    settled_at: new Date().toISOString(),',
        '  }',
        '  await kv.set(entry.key, JSON.stringify(update))',
        '  settlements.push({',
        '    slug: q.slug,',
        '    yes_token: q.yes_token,',
        '    rebate: update.cycle_rebate_usd,',
        '    as_cost: update.cycle_as_usd_gross_estimate,',
        '    net: update.cycle_net_usd_gross,',
        '  })',
        '}',
        '',
        '// Aggregate daily P&L from all settled quotes today.',
        'const allQuotes = await kv.list("makeryld:quotes:")',
        'const todayDateStr = new Date().toISOString().slice(0, 10)',
        'const todayKey = "makeryld:daily_pnl:" + todayDateStr',
        'let dailyPnl = 0',
        'for (const e of (allQuotes || [])) {',
        '  try {',
        '    const p = JSON.parse(e.value || "{}")',
        '    // typeof NaN === "number" so the existing check would not exclude NaN; add isFinite.',
        '    if (p.settled_at && p.settled_at.startsWith(todayDateStr) && Number.isFinite(p.cycle_net_usd_gross)) {',
        '      dailyPnl += p.cycle_net_usd_gross',
        '    }',
        '  } catch (err) { /* skip */ }',
        '}',
        'await kv.set(todayKey, JSON.stringify({ pnl_usd_gross: Number(dailyPnl.toFixed(4)), computed_at: new Date().toISOString() }))',
        '',
        'await fs.promises.writeFile("/workspace/scratch/makeryld_summary.md", [',
        '  "# Maker Yield Executor — Cycle Summary",',
        '  "",',
        '  "Settled this cycle: " + settlements.length,',
        '  "Today P&L (USD, gross of fees outside rebate): " + dailyPnl.toFixed(4),',
        '  "",',
        '  ...settlements.map((s) => "- " + s.slug + " | rebate=$" + s.rebate.toFixed(4) + " | as=$" + s.as_cost.toFixed(4) + " | net=$" + s.net.toFixed(4)),',
        '].join("\\n"))',
        '',
        'export default {',
        '  settled_count: settlements.length,',
        '  daily_pnl_usd_gross: Number(dailyPnl.toFixed(4)),',
        '  settlements,',
        '}',
      ].join("\n"),
    },
  ],
})
