import defineWorkflow from "/runtime/tools/workflow/defineWorkflow"

export default defineWorkflow({
  version: 1,
  id: "volume-tier-trap-filter",
  name: "Volume-Tier Trap Filter",
  description:
    "Scan active Polymarket negRisk events, assign each a dollar-volume tier (flagship / mid / tail) based on lifetime event volume, depth-walk only events in the allowed tiers, and surface only tier-allowed real signals. Implements the dollar-weighted reframe from polymarket-edge as a runnable filter.",
  triggers: [{ manual: true }],
  inputs: [
    { name: "limit", type: "number", required: false, default: 100 },
    { name: "feeBufferBp", type: "number", required: false, default: 50 },
    { name: "minConstituents", type: "number", required: false, default: 3 },
    { name: "maxAbsDeviation", type: "number", required: false, default: 0.10 },
    { name: "flagshipFloorUsd", type: "number", required: false, default: 1000000 },
    { name: "midFloorUsd", type: "number", required: false, default: 100000 },
    { name: "allowFlagship", type: "boolean", required: false, default: true },
    { name: "allowMid", type: "boolean", required: false, default: false },
    { name: "allowTail", type: "boolean", required: false, default: false },
    { name: "depthSize1", type: "number", required: false, default: 50 },
    { name: "depthSize2", type: "number", required: false, default: 500 },
    { name: "depthSize3", type: "number", required: false, default: 5000 },
    { name: "snapshotPrefix", type: "string", required: false, default: "voltier:" },
  ],
  output_mode: "inline",
  steps: [
    {
      id: "fetch_and_register",
      name: "Fetch active Polymarket events and capture the auto-registered SQL table name",
      type: "ts",
      timeout: 60000,
      allow: ["fetchPolymarketData"],
      code: [
        '// Self-bootstrap: invoke host-tools fetchPolymarketData via exec (the bash payload',
        '// budget is higher than the callTool ts-exec budget so dataset:"events" works here).',
        '// At limit=5 the call completes in ~1.6s. The host tool auto-registers the resulting',
        '// events table as `fetchPolymarketData_<hash>`.',
        'try {',
        '  await exec("mkdir -p /workspace/scratch && host-tools fetchPolymarketData \'{\\"dataset\\":\\"events\\",\\"active\\":true,\\"limit\\":5}\' --json-output-only > /workspace/scratch/voltier_bootstrap.txt 2>&1")',
        '} catch (e) {',
        '  // sqlite_master discovery will fall back to any pre-existing table',
        '}',
        '',
        '// Discover the latest auto-registered table.',
        'const tableQuery = await sql("SELECT name FROM sqlite_master WHERE type=\'table\' AND name LIKE \'fetchPolymarketData_%\' ORDER BY ROWID DESC LIMIT 1")',
        'const sourceTable = (tableQuery && tableQuery[0] && tableQuery[0].name) || null',
        '',
        'let tableName',
        'let rowCount = 0',
        'if (sourceTable) {',
        '  // Alias + dedup-by-market_id (host tool appends across calls within a session).',
        '  await exec("sql query \'DROP TABLE IF EXISTS polymarket_voltier_raw\'")',
        '  await exec("sql query \'CREATE TABLE polymarket_voltier_raw AS SELECT * FROM " + sourceTable + " WHERE rowid IN (SELECT MAX(rowid) FROM " + sourceTable + " GROUP BY market_id)\'")',
        '  const countResult = await sql("SELECT COUNT(*) AS n FROM polymarket_voltier_raw")',
        '  rowCount = Number((countResult && countResult[0] && countResult[0].n) || 0)',
        '  tableName = "polymarket_voltier_raw"',
        '} else {',
        '  tableName = "polymarket_voltier_raw"',
        '  rowCount = 0',
        '}',
        '',
        'const fetchMeta = {',
        '  table: tableName,',
        '  fetched: rowCount,',
        '  timestamp: new Date().toISOString(),',
        '}',
        'await kv.set("voltier:current_table", JSON.stringify(fetchMeta))',
        '',
        'export default fetchMeta',
      ].join("\n"),
    },
    {
      id: "tier_and_flag",
      name: "Compute event sum-of-yes, apply negRisk sanity filter, assign volume tier, filter by allowed tiers",
      type: "ts",
      depends_on: ["fetch_and_register"],
      timeout: 30000,
      code: [
        'const feeBufferBp = 50',
        'const minConstituents = 3',
        'const maxAbsDeviation = 0.10',
        'const flagshipFloorUsd = 1000000',
        'const midFloorUsd = 100000',
        'const allowFlagship = true',
        'const allowMid = false',
        'const allowTail = false',
        '',
        'const tableMeta = await kv.get("voltier:current_table")',
        'const tableMetaParsed = tableMeta ? JSON.parse(tableMeta.value || tableMeta) : null',
        'const tableName = (tableMetaParsed && tableMetaParsed.table) || "polymarket_voltier_raw"',
        '',
        'const aggSql =',
        '  "SELECT event_slug, event_title, COUNT(*) AS n, " +',
        '  "ROUND(SUM(CAST(yes_price AS REAL)), 6) AS sum_yes, " +',
        '  "ROUND(SUM(CAST(volume_total_usd AS REAL)), 0) AS ev_vol " +',
        '  "FROM " + tableName + " " +',
        '  "WHERE event_slug IS NOT NULL AND CAST(hours_until_end AS REAL) > 0 " +',
        '  "GROUP BY event_slug, event_title " +',
        '  "HAVING n >= " + minConstituents',
        '',
        'const allRows = await sql(aggSql)',
        '',
        '// Sanity filter: only real negRisk events (sum_yes within 0.10 of 1.0)',
        'const negRiskCandidates = allRows.filter((r) => Math.abs(Number(r.sum_yes) - 1.0) <= maxAbsDeviation)',
        '',
        'function tierFor(evVol) {',
        '  if (evVol >= flagshipFloorUsd) return "flagship"',
        '  if (evVol >= midFloorUsd) return "mid"',
        '  return "tail"',
        '}',
        '',
        'function tierAllowed(tier) {',
        '  if (tier === "flagship") return allowFlagship',
        '  if (tier === "mid") return allowMid',
        '  return allowTail',
        '}',
        '',
        'const allFlagged = []',
        'const filtered = []',
        'const tierCounts = { flagship: 0, mid: 0, tail: 0 }',
        '',
        'for (const r of negRiskCandidates) {',
        '  const sumYes = Number(r.sum_yes)',
        '  const evVol = Number(r.ev_vol || 0)',
        '  const deviationBp = Math.abs(sumYes - 1.0) * 10000',
        '  if (deviationBp <= feeBufferBp) continue',
        '  const direction = sumYes > 1.0 ? "sell" : "buy"',
        '  const tier = tierFor(evVol)',
        '  tierCounts[tier] = (tierCounts[tier] || 0) + 1',
        '  const candidate = {',
        '    event_slug: r.event_slug,',
        '    event_title: r.event_title,',
        '    n_constituents: Number(r.n),',
        '    sum_yes: sumYes,',
        '    deviation_bp: Math.round(deviationBp),',
        '    ev_vol: evVol,',
        '    direction,',
        '    tier,',
        '  }',
        '  allFlagged.push(candidate)',
        '  if (tierAllowed(tier)) filtered.push(candidate)',
        '}',
        'allFlagged.sort((a, b) => b.ev_vol - a.ev_vol)',
        'filtered.sort((a, b) => b.ev_vol - a.ev_vol)',
        '',
        'const totalEvVol = allFlagged.reduce((s, e) => s + (e.ev_vol || 0), 0)',
        'const filteredEvVol = filtered.reduce((s, e) => s + (e.ev_vol || 0), 0)',
        'const dollarShare = totalEvVol > 0 ? filteredEvVol / totalEvVol : 0',
        '',
        'const now = new Date().toISOString()',
        'await fs.promises.writeFile(',
        '  "/workspace/scratch/voltier_filtered.json",',
        '  JSON.stringify(filtered, null, 2)',
        ')',
        '',
        'const breakdown = {',
        '  timestamp: now,',
        '  totalEvents: allRows.length,',
        '  negRiskEvents: negRiskCandidates.length,',
        '  filteredOutAsNonNegRisk: allRows.length - negRiskCandidates.length,',
        '  tierCounts,',
        '  totalFlagged: allFlagged.length,',
        '  filteredCount: filtered.length,',
        '  totalFlaggedDollarVol: totalEvVol,',
        '  filteredDollarVol: filteredEvVol,',
        '  allowedTiersDollarShare: Number(dollarShare.toFixed(4)),',
        '}',
        'await kv.set("voltier:latest_breakdown", JSON.stringify(breakdown))',
        '',
        'export default {',
        '  ...breakdown,',
        '  topFiltered: filtered.slice(0, 5),',
        '}',
      ].join("\n"),
    },
    {
      id: "walk_and_surface",
      name: "Depth-walk tier-allowed flagged events and surface real signals",
      type: "ts",
      depends_on: ["tier_and_flag"],
      timeout: 180000,
      allow: ["getPredictionOrderbook"],
      code: [
        'const depthSize1 = 50',
        'const depthSize2 = 500',
        'const depthSize3 = 5000',
        '',
        'const tableMeta = await kv.get("voltier:current_table")',
        'const tableMetaParsed = tableMeta ? JSON.parse(tableMeta.value || tableMeta) : null',
        'const tableName = (tableMetaParsed && tableMetaParsed.table) || "polymarket_voltier_raw"',
        '',
        'const raw = await fs.promises',
        '  .readFile("/workspace/scratch/voltier_filtered.json", "utf8")',
        '  .catch(() => "[]")',
        'const filtered = JSON.parse(raw)',
        '',
        'const sizes = [depthSize1, depthSize2, depthSize3]',
        'const real = []',
        'const marginal = []',
        'const trap = []',
        '',
        '// One SQL fetch for all constituents; group in JS to avoid SQL injection vector.',
        'const allConstSql =',
        '  "SELECT event_slug, slug, " +',
        '  "SUBSTR(clob_token_ids, 1, INSTR(clob_token_ids, \\",\\") - 1) AS yes_token " +',
        '  "FROM " + tableName + " " +',
        '  "WHERE CAST(hours_until_end AS REAL) > 0"',
        'const allConstituents = await sql(allConstSql)',
        'const byEventSlug = {}',
        'for (const c of (allConstituents || [])) {',
        '  const slug = c.event_slug',
        '  if (!slug) continue',
        '  if (!byEventSlug[slug]) byEventSlug[slug] = []',
        '  byEventSlug[slug].push(c)',
        '}',
        '',
        'for (const ev of filtered.slice(0, 10)) {',
        '  const constituents = byEventSlug[ev.event_slug] || []',
        '  if (constituents.length === 0) continue',
        '  let walkedConstituents = 0',
        '',
        '  const side = ev.direction === "sell" ? "sell" : "buy"',
        '  const basketSum = { [depthSize1]: 0, [depthSize2]: 0, [depthSize3]: 0 }',
        '  let throttle = null',
        '',
        '  // Parallel orderbook walk via Promise.all (sequential calls exceed the step timeout)',
        '  const constituentsToWalk = constituents.filter((c) => c.yes_token)',
        '  const results = await Promise.all(constituentsToWalk.map(async (c) => {',
        '    try {',
        '      const ob = await callTool("getPredictionOrderbook", {',
        '        tokenId: String(c.yes_token),',
        '        slippageSizes: sizes,',
        '      })',
        '      return { c, ob }',
        '    } catch (e) {',
        '      return { c, ob: null }',
        '    }',
        '  }))',
        '',
        '  for (const { c, ob } of results) {',
        '    if (!ob) continue',
        '    const slip = (ob && ob.slippageEstimates) || []',
        '    for (const s of sizes) {',
        '      const est = slip.find((x) => x.size === s && x.side === side)',
        '      if (!est) continue',
        '      basketSum[s] = (basketSum[s] || 0) + Number(est.avgFillPrice)',
        '    }',
        '    const fillable = slip.filter((x) => x.side === side && x.fullyFillable)',
        '    const maxFillable = fillable.reduce((m, x) => Math.max(m, x.size), 0)',
        '    if (!throttle || maxFillable < throttle.maxFillable) {',
        '      throttle = { slug: c.slug, maxFillable }',
        '    }',
        '    walkedConstituents++',
        '  }',
        '',
        '  function gapBpAt(size) {',
        '    const sum = basketSum[size]',
        '    if (!sum) return 0',
        '    return side === "sell" ? (sum - 1.0) * 10000 : (1.0 - sum) * 10000',
        '  }',
        '',
        '  const gap50 = Math.round(gapBpAt(depthSize1))',
        '  const gap500 = Math.round(gapBpAt(depthSize2))',
        '  const gap5k = Math.round(gapBpAt(depthSize3))',
        '',
        '  const walkComplete = walkedConstituents === ev.n_constituents',
        '  const classified = {',
        '    event_slug: ev.event_slug,',
        '    event_title: ev.event_title,',
        '    tier: ev.tier,',
        '    direction: ev.direction,',
        '    n_constituents: ev.n_constituents,',
        '    walked_constituents: walkedConstituents,',
        '    walk_complete: walkComplete,',
        '    sum_yes: ev.sum_yes,',
        '    top_of_book_gap_bp: ev.deviation_bp,',
        '    gap_at_50_bp: gap50,',
        '    gap_at_500_bp: gap500,',
        '    gap_at_5000_bp: gap5k,',
        '    throttle,',
        '    ev_vol: ev.ev_vol,',
        '  }',
        '',
        '  if (gap50 < 0) {',
        '    trap.push(classified)',
        '  } else if (!walkComplete) {',
        '    marginal.push(classified)',
        '  } else if (gap500 < 50) {',
        '    marginal.push(classified)',
        '  } else {',
        '    real.push(classified)',
        '  }',
        '}',
        '',
        'const timestamp = new Date().toISOString()',
        'const result = { timestamp, real, marginal, trap }',
        'await kv.set("voltier:latest_surfaced", JSON.stringify({ timestamp, real }))',
        'await fs.promises.writeFile(',
        '  "/workspace/scratch/voltier_classified.json",',
        '  JSON.stringify(result, null, 2)',
        ')',
        '',
        'const lines = []',
        'lines.push("# Volume-Tier Trap Filter Scan")',
        'lines.push("")',
        'lines.push("Timestamp: " + timestamp)',
        'lines.push("Real signals (tier-allowed): " + real.length)',
        'lines.push("Marginal signals (tier-allowed): " + marginal.length)',
        'lines.push("Traps (tier-allowed): " + trap.length)',
        'lines.push("")',
        'if (real.length > 0) {',
        '  lines.push("## Tier-allowed real signals")',
        '  for (const r of real) {',
        '    const evVolFmt = "$" + Math.round(r.ev_vol).toLocaleString()',
        '    const thr = r.throttle ? (r.throttle.slug + " (max " + r.throttle.maxFillable + ")") : "n/a"',
        '    lines.push(',
        '      "- **" + r.event_slug + "** [" + r.tier + "] (" + r.direction + ") | " +',
        '      "top " + r.top_of_book_gap_bp + "bp | $500 " + r.gap_at_500_bp + "bp | $5K " + r.gap_at_5000_bp + "bp | ev_vol " + evVolFmt + " | throttle: " + thr',
        '    )',
        '  }',
        '}',
        'await fs.promises.writeFile("/workspace/scratch/voltier_summary.md", lines.join("\\n"))',
        '',
        'export default {',
        '  real_count: real.length,',
        '  marginal_count: marginal.length,',
        '  trap_count: trap.length,',
        '  real,',
        '}',
      ].join("\n"),
    },
  ],
})
