import defineWorkflow from "/runtime/tools/workflow/defineWorkflow"

export default defineWorkflow({
  version: 1,
  id: "negrisk-maker-executor",
  name: "NegRisk Maker Arbitrage Executor",
  description:
    "Consume depth-verified negRisk arbitrage signals from KV, place maker orders on each constituent under risk caps, monitor positions through basket convergence, and report realised P&L. Defaults to dryRun: true.",
  triggers: [{ manual: true }],
  inputs: [
    { name: "signalKeyArb", type: "string", required: false, default: "negrisk:latest_classified" },
    { name: "signalKeyTier", type: "string", required: false, default: "voltier:latest_surfaced" },
    { name: "maxCapitalPerEventUsd", type: "number", required: false, default: 5000 },
    { name: "maxOpenPositions", type: "number", required: false, default: 3 },
    { name: "maxDailyNotionalUsd", type: "number", required: false, default: 20000 },
    { name: "maxDailyLossUsd", type: "number", required: false, default: 200 },
    { name: "makerOnly", type: "boolean", required: false, default: true },
    { name: "makerLimitPriceOffsetBp", type: "number", required: false, default: 5 },
    { name: "closeBandBp", type: "number", required: false, default: 25 },
    { name: "dryRun", type: "boolean", required: false, default: true },
    { name: "notionalUsdOverride", type: "number", required: false, default: 0 },
  ],
  output_mode: "inline",
  steps: [
    {
      id: "load_state",
      name: "Load current positions, daily P&L, kill-switch state from KV",
      type: "ts",
      timeout: 15000,
      code: [
        'const todayKey = "executor:daily_pnl:" + new Date().toISOString().slice(0, 10)',
        'const dailyPnlRaw = await kv.get(todayKey)',
        'const dailyPnl = dailyPnlRaw ? (JSON.parse(dailyPnlRaw.value || dailyPnlRaw).pnl_usd || 0) : 0',
        '',
        'const killRaw = await kv.get("executor:kill_switch_state")',
        'const killState = killRaw ? (JSON.parse(killRaw.value || killRaw).state || "armed") : "armed"',
        '',
        'const positionsRaw = await kv.list("executor:positions:")',
        'const openPositions = []',
        'for (const entry of (positionsRaw || [])) {',
        '  try {',
        '    const p = JSON.parse(entry.value || "{}")',
        '    if (p.status === "open" || p.status === "opening") openPositions.push(p)',
        '  } catch (e) { /* skip corrupted entries */ }',
        '}',
        '',
        'const state = {',
        '  daily_pnl_usd: dailyPnl,',
        '  kill_switch: killState,',
        '  open_positions: openPositions,',
        '  open_positions_count: openPositions.length,',
        '  timestamp: new Date().toISOString(),',
        '}',
        'await kv.set("executor:current_state", JSON.stringify(state))',
        '',
        'export default state',
      ].join("\n"),
    },
    {
      id: "evaluate_signals",
      name: "Read sibling-recipe signal KV state, identify new arb opportunities not already positioned",
      type: "ts",
      depends_on: ["load_state"],
      timeout: 15000,
      code: [
        'const signalKeyArb = "negrisk:latest_classified"',
        'const signalKeyTier = "voltier:latest_surfaced"',
        '',
        'function loadSignals(raw) {',
        '  if (!raw) return []',
        '  try {',
        '    const parsed = JSON.parse(raw.value || raw)',
        '    return Array.isArray(parsed.real) ? parsed.real : []',
        '  } catch (e) { return [] }',
        '}',
        '',
        'const arbRaw = await kv.get(signalKeyArb)',
        'const tierRaw = await kv.get(signalKeyTier)',
        'const arbSignals = loadSignals(arbRaw)',
        'const tierSignals = loadSignals(tierRaw)',
        '',
        '// Prefer tier-filtered signals; fall back to surfacer if filter is empty.',
        'const candidateSignals = tierSignals.length > 0 ? tierSignals : arbSignals',
        '',
        'const stateRaw = await kv.get("executor:current_state")',
        'const state = stateRaw ? JSON.parse(stateRaw.value || stateRaw) : { open_positions: [] }',
        'const positionedSlugs = new Set((state.open_positions || []).map((p) => p.event_slug))',
        '',
        'const opportunities = []',
        'for (const sig of candidateSignals) {',
        '  if (positionedSlugs.has(sig.event_slug)) continue',
        '  // Require depth-verified real classification AND complete walk.',
        '  if (sig.walk_complete === false) continue',
        '  if (typeof sig.gap_at_500_bp !== "number" || sig.gap_at_500_bp < 50) continue',
        '  // Reject if the basket has a constituent with empty bid book at throttle scale.',
        '  // A basket with a zero-depth leg cannot fully open; opening would leave',
        '  // persistent mark-to-market exposure on the stuck leg.',
        '  if (sig.throttle && Number(sig.throttle.maxFillable) === 0) continue',
        '  opportunities.push(sig)',
        '}',
        'opportunities.sort((a, b) => (b.ev_vol || 0) - (a.ev_vol || 0))',
        '',
        '// Persist opportunities for risk_gate to consume (KV is primary; file is mirror for debuggability).',
        'const opportunitiesPayload = { opportunities, timestamp: new Date().toISOString() }',
        'await kv.set("executor:last_opportunities", JSON.stringify(opportunitiesPayload))',
        'await fs.promises.writeFile(',
        '  "/workspace/scratch/executor_opportunities.json",',
        '  JSON.stringify(opportunitiesPayload, null, 2)',
        ')',
        '',
        'export default {',
        '  arbSignalCount: arbSignals.length,',
        '  tierSignalCount: tierSignals.length,',
        '  newOpportunities: opportunities.length,',
        '  opportunities: opportunities.slice(0, 5),',
        '}',
      ].join("\n"),
    },
    {
      id: "risk_gate",
      name: "Apply capital, position-count, daily-loss, and kill-switch caps",
      type: "ts",
      depends_on: ["evaluate_signals"],
      timeout: 10000,
      code: [
        'const maxCapitalPerEventUsd = 5000',
        'const maxOpenPositions = 3',
        'const maxDailyNotionalUsd = 20000',
        'const maxDailyLossUsd = 200',
        '',
        'const stateRaw = await kv.get("executor:current_state")',
        'const state = stateRaw ? JSON.parse(stateRaw.value || stateRaw) : { daily_pnl_usd: 0, kill_switch: "armed", open_positions: [] }',
        '',
        'const dailyNotionalUsedRaw = await kv.get("executor:daily_notional:" + new Date().toISOString().slice(0, 10))',
        'const dailyNotionalUsed = dailyNotionalUsedRaw ? (JSON.parse(dailyNotionalUsedRaw.value || dailyNotionalUsedRaw).usd || 0) : 0',
        '',
        'const opportunitiesRaw = await fs.promises.readFile("/workspace/scratch/executor_opportunities.json", "utf8").catch(() => null)',
        '',
        'const blocks = []',
        'const allowed = []',
        '',
        'if (state.kill_switch === "tripped") {',
        '  blocks.push({ reason: "kill_switch_tripped" })',
        '} else if (state.daily_pnl_usd < -maxDailyLossUsd) {',
        '  await kv.set("executor:kill_switch_state", JSON.stringify({ state: "tripped", trippedAt: new Date().toISOString(), reason: "daily_loss_cap_exceeded" }))',
        '  blocks.push({ reason: "daily_loss_cap_exceeded", daily_pnl_usd: state.daily_pnl_usd })',
        '}',
        '',
        'if (blocks.length === 0) {',
        '  const remainingDailyNotional = Math.max(0, maxDailyNotionalUsd - dailyNotionalUsed)',
        '  const remainingPositionSlots = Math.max(0, maxOpenPositions - (state.open_positions || []).length)',
        '',
        '  if (remainingPositionSlots <= 0) {',
        '    blocks.push({ reason: "max_open_positions_reached", count: state.open_positions.length })',
        '  } else if (remainingDailyNotional <= 0) {',
        '    blocks.push({ reason: "max_daily_notional_reached", used: dailyNotionalUsed })',
        '  } else {',
        '    // We still need the opportunities to gate against. Read from previous step output via KV.',
        '    const evalStateRaw = await kv.get("executor:last_opportunities")',
        '    const evalState = evalStateRaw ? JSON.parse(evalStateRaw.value || evalStateRaw) : { opportunities: [] }',
        '    const ops = evalState.opportunities || []',
        '',
        '    let remainingBudget = remainingDailyNotional',
        '    for (const op of ops) {',
        '      if (allowed.length >= remainingPositionSlots) break',
        '      const sizing = Math.min(maxCapitalPerEventUsd, remainingBudget)',
        '      if (sizing < 100) {',
        '        blocks.push({ event_slug: op.event_slug, reason: "remaining_budget_below_min", sizing })',
        '        break',
        '      }',
        '      allowed.push({ ...op, allocated_usd: sizing })',
        '      remainingBudget -= sizing',
        '    }',
        '  }',
        '}',
        '',
        'await kv.set("executor:risk_gate_result", JSON.stringify({ timestamp: new Date().toISOString(), allowed, blocks }))',
        '',
        'export default {',
        '  allowedCount: allowed.length,',
        '  blockCount: blocks.length,',
        '  blocks,',
        '  allowed: allowed.slice(0, 3),',
        '}',
      ].join("\n"),
    },
    {
      id: "plan_and_execute",
      name: "Compute per-constituent maker order intents and submit them when dryRun is false",
      type: "ts",
      depends_on: ["risk_gate"],
      timeout: 60000,
      allow: ["getPredictionOrderbook", "tradePredictionMarket", "managePredictionOrders"],
      code: [
        '// Defense-in-depth: trading-relevant parameters are HARDCODED here rather than',
        '// sourced from recipe inputs. Recipe inputs for these (dryRun, makerOnly,',
        '// makerLimitPriceOffsetBp, notionalUsdOverride) are documented but require explicit',
        '// edits to this file to take effect. Live promotion requires three traceable changes:',
        '//   1. set `const dryRun = false`',
        '//   2. uncomment the `managePredictionOrders` block in this step',
        '//   3. uncomment the `closePredictionPosition` block in monitor_and_close',
        'const makerOnly = true',
        'const makerLimitPriceOffsetBp = 5',
        'const dryRun = true',
        'const notionalUsdOverride = 0',
        '',
        'const gateRaw = await kv.get("executor:risk_gate_result")',
        'const gate = gateRaw ? JSON.parse(gateRaw.value || gateRaw) : { allowed: [] }',
        'const allowed = gate.allowed || []',
        '',
        'const intents = []',
        'const errors = []',
        '',
        'for (const op of allowed) {',
        '  // Each op carries its event_slug, direction (sell or buy), n_constituents, ev_vol, allocated_usd.',
        '  // We need fresh per-constituent orderbooks to compute the order intents.',
        '  const constituents = op.constituents_yes_tokens || []',
        '  if (constituents.length === 0) {',
        '    errors.push({ event_slug: op.event_slug, reason: "no_constituents_in_signal" })',
        '    continue',
        '  }',
        '',
        '  const sizePerConstituent = (op.allocated_usd || 0) / constituents.length',
        '  const intentForEvent = {',
        '    event_slug: op.event_slug,',
        '    direction: op.direction,',
        '    allocated_usd: op.allocated_usd,',
        '    size_per_constituent_usd: sizePerConstituent,',
        '    orders: [],',
        '    submission_status: dryRun ? "dry_run" : "pending",',
        '    timestamp: new Date().toISOString(),',
        '  }',
        '',
        '  for (const tokenId of constituents) {',
        '    let ob',
        '    try {',
        '      ob = await callTool("getPredictionOrderbook", { tokenId: String(tokenId), slippageSizes: [50, sizePerConstituent] })',
        '    } catch (e) {',
        '      errors.push({ event_slug: op.event_slug, token: tokenId, reason: "orderbook_call_failed" })',
        '      continue',
        '    }',
        '    const summary = (ob && ob.summary) || {}',
        '    const bestBid = Number(summary.bestBid || 0)',
        '    const bestAsk = Number(summary.bestAsk || 0)',
        '',
        '    // Sell-side basket: post a LIMIT SELL at bestBid + offsetBp (slightly above best bid to be visible but rebate-positive).',
        '    // Buy-side basket: post a LIMIT BUY at bestAsk - offsetBp (slightly below best ask).',
        '    const offsetPrice = makerLimitPriceOffsetBp / 10000',
        '    let limitPrice',
        '    let side',
        '    if (op.direction === "sell") {',
        '      limitPrice = Math.max(0.001, bestBid + offsetPrice)',
        '      side = "sell"',
        '    } else {',
        '      limitPrice = Math.min(0.999, bestAsk - offsetPrice)',
        '      side = "buy"',
        '    }',
        '',
        '    const order = {',
        '      tokenId: String(tokenId),',
        '      side,',
        '      limit_price: Number(limitPrice.toFixed(4)),',
        '      size_usd: Number(sizePerConstituent.toFixed(2)),',
        '      expected_shares: Number((sizePerConstituent / limitPrice).toFixed(2)),',
        '      maker_only: makerOnly,',
        '    }',
        '    intentForEvent.orders.push(order)',
        '',
        '    if (!dryRun) {',
        '      // PRODUCTION PATH — explicit operator authorization required.',
        '      // This is intentionally NOT exercised in the as-shipped recipe (dryRun defaults to true).',
        '      // The actual submission would call managePredictionOrders to place a maker limit order.',
        '      try {',
        '        // const submitResult = await callTool("managePredictionOrders", {',
        '        //   action: "create",',
        '        //   tokenId: String(tokenId),',
        '        //   side,',
        '        //   orderType: makerOnly ? "limit" : "market",',
        '        //   price: order.limit_price,',
        '        //   sizeUsd: order.size_usd,',
        '        // })',
        '        // order.submission_id = submitResult.id',
        '        // order.submission_status = "submitted"',
        '        order.submission_status = "live_path_disabled_in_workflow"',
        '      } catch (e) {',
        '        order.submission_status = "failed"',
        '        order.submission_error = String(e)',
        '      }',
        '    }',
        '  }',
        '',
        '  intents.push(intentForEvent)',
        '',
        '  // Persist the per-event position record',
        '  const posKey = "executor:positions:" + op.event_slug',
        '  await kv.set(posKey, JSON.stringify({',
        '    event_slug: op.event_slug,',
        '    status: dryRun ? "dry_run" : "opening",',
        '    direction: op.direction,',
        '    allocated_usd: op.allocated_usd,',
        '    orders: intentForEvent.orders,',
        '    opened_at: new Date().toISOString(),',
        '    entry_sum_yes: op.sum_yes,',
        '    last_seen_sum_yes: op.sum_yes,',
        '  }))',
        '}',
        '',
        'await fs.promises.writeFile("/workspace/scratch/executor_cycle.json", JSON.stringify({ intents, errors }, null, 2))',
        '',
        'export default {',
        '  intentCount: intents.length,',
        '  errorCount: errors.length,',
        '  dryRun,',
        '  totalAllocatedUsd: intents.reduce((s, i) => s + (i.allocated_usd || 0), 0),',
        '}',
      ].join("\n"),
    },
    {
      id: "monitor_and_close",
      name: "Check open positions for basket convergence; close those within closeBandBp of fair value",
      type: "ts",
      depends_on: ["plan_and_execute"],
      timeout: 60000,
      allow: ["getPredictionOrderbook", "closePredictionPosition", "managePredictionOrders"],
      code: [
        'const closeBandBp = 25',
        'const dryRun = true',
        '',
        'const positionsRaw = await kv.list("executor:positions:")',
        'const cycleResults = []',
        '',
        'for (const entry of (positionsRaw || [])) {',
        '  let position',
        '  try { position = JSON.parse(entry.value || "{}") } catch (e) { continue }',
        '  if (position.status !== "opening" && position.status !== "open" && position.status !== "dry_run") continue',
        '',
        '  // Refresh basket sum_yes by re-querying constituents.',
        '  let currentSum = 0',
        '  let walked = 0',
        '  for (const order of (position.orders || [])) {',
        '    let ob',
        '    try {',
        '      ob = await callTool("getPredictionOrderbook", { tokenId: order.tokenId, slippageSizes: [50] })',
        '    } catch (e) { continue }',
        '    const bestBid = (ob && ob.summary && Number(ob.summary.bestBid)) || 0',
        '    const bestAsk = (ob && ob.summary && Number(ob.summary.bestAsk)) || 0',
        '    const mid = (bestBid + bestAsk) / 2',
        '    if (mid > 0) {',
        '      currentSum += mid',
        '      walked++',
        '    }',
        '  }',
        '',
        '  const distanceFromFair = Math.abs(currentSum - 1.0) * 10000',
        '  const shouldClose = walked > 0 && distanceFromFair < closeBandBp',
        '',
        '  const update = {',
        '    ...position,',
        '    last_seen_sum_yes: currentSum,',
        '    last_seen_at: new Date().toISOString(),',
        '    walked_constituents: walked,',
        '  }',
        '',
        '  if (shouldClose) {',
        '    // CLOSE-OUT PATH — explicit operator authorization required for live.',
        '    if (dryRun) {',
        '      update.status = "closed_dry_run"',
        '      // Estimated P&L is anchored on entry_sum_yes (set at opening, never overwritten),',
        '      // not last_seen_sum_yes (mark-to-market, updated each cycle). The formula yields',
        '      // a GROSS basket-relative gap closure, not net of fees/rebates/AS. This matches',
        '      // the TOB-quality-anchored upper-bound number in PROFITABILITY_ANALYSIS.md;',
        '      // realised maker P&L will be lower depending on actual fill quality and AS.',
        '      const entrySum = position.entry_sum_yes || position.last_seen_sum_yes || (position.direction === "sell" ? 1.02 : 0.98)',
        '      const pnlBp = position.direction === "sell"',
        '        ? (entrySum - currentSum) * 10000',
        '        : (currentSum - entrySum) * 10000',
        '      update.estimated_pnl_bp_gross = Math.round(pnlBp)',
        '      update.estimated_pnl_usd_gross = Math.round(((position.allocated_usd || 0) * pnlBp) / 10000)',
        '      update.closed_at = new Date().toISOString()',
        '    } else {',
        '      // Production close-out would iterate orders and call closePredictionPosition or',
        '      // managePredictionOrders to flatten each constituent.',
        '      update.status = "live_path_disabled_in_workflow"',
        '    }',
        '  }',
        '',
        '  await kv.set(entry.key, JSON.stringify(update))',
        '  cycleResults.push({ event_slug: update.event_slug, status: update.status, distance_bp: Math.round(distanceFromFair), estimated_pnl_usd_gross: update.estimated_pnl_usd_gross })',
        '}',
        '',
        '// Aggregate daily P&L from closed positions',
        'const allPositions = await kv.list("executor:positions:")',
        'const todayKey = "executor:daily_pnl:" + new Date().toISOString().slice(0, 10)',
        'let dailyPnl = 0',
        'for (const e of (allPositions || [])) {',
        '  try {',
        '    const p = JSON.parse(e.value || "{}")',
        '    if (p.closed_at && p.closed_at.startsWith(new Date().toISOString().slice(0, 10))) {',
        '      dailyPnl += Number(p.estimated_pnl_usd_gross || 0)',
        '    }',
        '  } catch (err) { /* skip */ }',
        '}',
        'await kv.set(todayKey, JSON.stringify({ pnl_usd: dailyPnl, computed_at: new Date().toISOString() }))',
        '',
        'await fs.promises.writeFile("/workspace/scratch/executor_summary.md", [',
        '  "# Executor cycle summary",',
        '  "",',
        '  "Cycle results: " + cycleResults.length,',
        '  "Today P&L (USD): " + dailyPnl,',
        '  "",',
        '  ...cycleResults.map((r) => "- " + r.event_slug + " | status=" + r.status + " | distance_bp=" + r.distance_bp + " | est_pnl_usd_gross=" + (r.estimated_pnl_usd_gross || 0)),',
        '].join("\\n"))',
        '',
        'export default {',
        '  cycle_results_count: cycleResults.length,',
        '  daily_pnl_usd: dailyPnl,',
        '  cycleResults,',
        '}',
      ].join("\n"),
    },
  ],
})
