import defineWorkflow from "/runtime/tools/workflow/defineWorkflow"

export default defineWorkflow({
  version: 1,
  id: "negrisk-event-arbitrage-surfacer",
  name: "NegRisk Event Arbitrage Surfacer",
  description:
    "Scan active Polymarket negRisk events for sum-of-yes deviations from $1.00 and depth-walk constituent orderbooks to surface only basket arbitrages that clear at meaningful size.",
  triggers: [{ manual: true }],
  inputs: [
    { name: "limit", type: "number", required: false, default: 500 },
    { name: "feeBufferBp", type: "number", required: false, default: 50 },
    { name: "minConstituents", type: "number", required: false, default: 3 },
    { name: "maxAbsDeviation", type: "number", required: false, default: 0.10 },
    { name: "minEventVolumeUsd", type: "number", required: false, default: 0 },
    { name: "depthSize1", type: "number", required: false, default: 50 },
    { name: "depthSize2", type: "number", required: false, default: 500 },
    { name: "depthSize3", type: "number", required: false, default: 5000 },
    { name: "maxEventsToWalk", type: "number", required: false, default: 20 },
    { name: "snapshotPrefix", type: "string", required: false, default: "negrisk:" },
  ],
  output_mode: "inline",
  steps: [
    {
      id: "fetch_and_register",
      name: "Fetch active Polymarket events and capture the auto-registered SQL table name",
      type: "ts",
      timeout: 60000,
      allow: ["fetchPolymarketData"],
      code: [
        '// `fetchPolymarketData({ dataset: "events" })` via callTool inside the workflow runtime',
        '// crashes the ts-exec response budget. We bootstrap via `exec` (shell payload budget',
        '// is higher). At limit=5 the host-tool call completes in ~1.6s and auto-registers',
        '// the resulting events table as `fetchPolymarketData_<hash>`.',
        '//',
        '// Self-bootstrapping: no operator setup required. If a previous run already populated',
        '// a table, the new fetch refreshes it; sqlite_master discovery always uses the latest.',
        'try {',
        '  await exec("mkdir -p /workspace/scratch && host-tools fetchPolymarketData \'{\\"dataset\\":\\"events\\",\\"active\\":true,\\"limit\\":5}\' --json-output-only > /workspace/scratch/bootstrap.txt 2>&1")',
        '} catch (e) {',
        '  // bootstrap may fail under rare conditions; sqlite_master discovery will fall back',
        '  // to any pre-existing table from a prior session if needed.',
        '}',
        '',
        '// Discover the latest auto-registered fetchPolymarketData_* table.',
        'const tableQuery = await sql("SELECT name FROM sqlite_master WHERE type=\'table\' AND name LIKE \'fetchPolymarketData_%\' ORDER BY ROWID DESC LIMIT 1")',
        'let sourceTable = (tableQuery && tableQuery[0] && tableQuery[0].name) || null',
        '',
        '// Defense: refuse to interpolate any sourceTable name that does not match the expected',
        '// host-tool pattern, to harden against future drift in table-naming that could expose',
        '// a shell-quote or SQL-injection vector through the exec calls below.',
        'if (sourceTable && !/^fetchPolymarketData_[a-zA-Z0-9_]+$/.test(sourceTable)) {',
        '  sourceTable = null',
        '}',
        '',
        'let tableName',
        'let rowCount = 0',
        'if (sourceTable) {',
        '  // Alias to a known table name. Deduplicate by market_id keeping the latest occurrence',
        '  // (host tool appends to its auto-registered table across calls within a session, so',
        '  // the same market can appear multiple times with different prices).',
        '  await exec("sql query \'DROP TABLE IF EXISTS polymarket_negrisk_raw\'")',
        '  await exec("sql query \'CREATE TABLE polymarket_negrisk_raw AS SELECT * FROM " + sourceTable + " WHERE rowid IN (SELECT MAX(rowid) FROM " + sourceTable + " GROUP BY market_id)\'")',
        '  const countResult = await sql("SELECT COUNT(*) AS n FROM polymarket_negrisk_raw")',
        '  rowCount = Number((countResult && countResult[0] && countResult[0].n) || 0)',
        '  tableName = "polymarket_negrisk_raw"',
        '} else {',
        '  tableName = "polymarket_negrisk_raw"',
        '  rowCount = 0',
        '}',
        '',
        'const fetchMeta = {',
        '  table: tableName,',
        '  fetched: rowCount,',
        '  timestamp: new Date().toISOString(),',
        '}',
        'await kv.set("negrisk:current_table", JSON.stringify(fetchMeta))',
        '',
        'export default fetchMeta',
      ].join("\n"),
    },
    {
      id: "compute_event_gaps",
      name: "Aggregate sum-of-yes per event, apply negRisk sanity filter, flag deviation candidates",
      type: "ts",
      depends_on: ["fetch_and_register"],
      timeout: 30000,
      code: [
        'const feeBufferBp = 50',
        'const minConstituents = 3',
        'const maxAbsDeviation = 0.10',
        'const minEventVolumeUsd = 0',
        '',
        'const tableMeta = await kv.get("negrisk:current_table")',
        'const tableMetaParsed = tableMeta ? JSON.parse(tableMeta.value || tableMeta) : null',
        'let tableName = (tableMetaParsed && tableMetaParsed.table) || "polymarket_negrisk_raw"',
        '// Defense: refuse to interpolate non-conforming table names into SQL.',
        'if (!/^[a-zA-Z0-9_]+$/.test(tableName)) {',
        '  tableName = "polymarket_negrisk_raw"',
        '}',
        '',
        '// event_slug IS populated on the auto-registered dataset:"events" table. Standard SQL.',
        'const aggSql =',
        '  "SELECT event_slug, MIN(event_title) AS event_title, COUNT(*) AS n, " +',
        '  "ROUND(SUM(CAST(yes_price AS REAL)), 6) AS sum_yes, " +',
        '  "ROUND(SUM(CAST(volume_total_usd AS REAL)), 0) AS ev_vol " +',
        '  "FROM " + tableName + " " +',
        '  "WHERE event_slug IS NOT NULL AND CAST(hours_until_end AS REAL) > 0 " +',
        '  "GROUP BY event_slug " +',
        '  "HAVING n >= " + minConstituents',
        'const allRows = await sql(aggSql)',
        '',
        '// Sanity filter: real negRisk events have sum_yes near 1.0. Multi-option non-exclusive',
        '// events (price-tier baskets, multi-outcome polls with overlapping definitions) sum to',
        '// wildly different values and would be false positives if classified as arbitrage.',
        'const negRiskCandidates = allRows.filter((r) => Math.abs(Number(r.sum_yes) - 1.0) <= maxAbsDeviation)',
        '',
        'const flagged = []',
        'for (const r of negRiskCandidates) {',
        '  const sumYes = Number(r.sum_yes)',
        '  const evVol = Number(r.ev_vol || 0)',
        '  const deviationBp = Math.abs(sumYes - 1.0) * 10000',
        '  if (deviationBp <= feeBufferBp) continue',
        '  if (evVol < minEventVolumeUsd) continue',
        '  const direction = sumYes > 1.0 ? "sell" : "buy"',
        '  flagged.push({',
        '    event_slug: r.event_slug,',
        '    event_title: r.event_title,',
        '    n_constituents: Number(r.n),',
        '    sum_yes: sumYes,',
        '    deviation_bp: Math.round(deviationBp),',
        '    ev_vol: evVol,',
        '    direction,',
        '  })',
        '}',
        'flagged.sort((a, b) => b.ev_vol - a.ev_vol)',
        '',
        'const now = new Date().toISOString()',
        'const runKey = "negrisk:" + now.slice(0, 13)',
        'const snapshot = { timestamp: now, flagged, count: flagged.length, totalCandidates: allRows.length, negRiskCandidates: negRiskCandidates.length }',
        'await kv.set(runKey, JSON.stringify(snapshot))',
        'await kv.set("negrisk:latest_flagged", JSON.stringify(snapshot))',
        '',
        'await fs.promises.writeFile(',
        '  "/workspace/scratch/negrisk_flagged.json",',
        '  JSON.stringify(flagged, null, 2)',
        ')',
        '',
        'export default {',
        '  flaggedCount: flagged.length,',
        '  totalEvents: allRows.length,',
        '  negRiskEvents: negRiskCandidates.length,',
        '  filteredOutAsNonNegRisk: allRows.length - negRiskCandidates.length,',
        '  topEvents: flagged.slice(0, 5),',
        '}',
      ].join("\n"),
    },
    {
      id: "walk_depth_and_classify",
      name: "Walk constituent orderbook depth and classify each flagged event",
      type: "ts",
      depends_on: ["compute_event_gaps"],
      timeout: 180000,
      allow: ["getPredictionOrderbook"],
      code: [
        'const depthSize1 = 50',
        'const depthSize2 = 500',
        'const depthSize3 = 5000',
        'const maxEventsToWalk = 20',
        '',
        'const tableMeta = await kv.get("negrisk:current_table")',
        'const tableMetaParsed = tableMeta ? JSON.parse(tableMeta.value || tableMeta) : null',
        'let tableName = (tableMetaParsed && tableMetaParsed.table) || "polymarket_negrisk_raw"',
        '// Defense: refuse to interpolate non-conforming table names into SQL.',
        'if (!/^[a-zA-Z0-9_]+$/.test(tableName)) {',
        '  tableName = "polymarket_negrisk_raw"',
        '}',
        '',
        'const raw = await fs.promises',
        '  .readFile("/workspace/scratch/negrisk_flagged.json", "utf8")',
        '  .catch(() => "[]")',
        'const flagged = JSON.parse(raw)',
        '',
        'const sizes = [depthSize1, depthSize2, depthSize3]',
        'const real = []',
        'const marginal = []',
        'const trap = []',
        '',
        '// One SQL fetch for all constituents across all events, grouped in JS.',
        '// Avoids SQL injection vector that per-event WHERE-clause string concatenation would introduce.',
        'const allConstSql =',
        '  "SELECT event_slug, slug, " +',
        '  "CAST(yes_price AS REAL) AS yes_price, " +',
        '  "SUBSTR(clob_token_ids, 1, INSTR(clob_token_ids, \\",\\") - 1) AS yes_token " +',
        '  "FROM " + tableName + " " +',
        '  "WHERE CAST(hours_until_end AS REAL) > 0"',
        'const allConstituents = await sql(allConstSql)',
        'const byEventSlug = {}',
        'for (const c of (allConstituents || [])) {',
        '  const slug = c.event_slug',
        '  if (!slug) continue',
        '  if (!byEventSlug[slug]) byEventSlug[slug] = []',
        '  byEventSlug[slug].push(c)',
        '}',
        '',
        'for (const ev of flagged.slice(0, maxEventsToWalk)) {',
        '  const constituents = byEventSlug[ev.event_slug] || []',
        '  if (constituents.length === 0) continue',
        '',
        '  // Sell-side basket: sell each YES at best bid. Profit if sum > 1 (sold above the $1 guaranteed payout).',
        '  // Buy-side basket: buy each YES at best ask. Profit if sum < 1.',
        '  const side = ev.direction === "sell" ? "sell" : "buy"',
        '  const basketSum = { [depthSize1]: 0, [depthSize2]: 0, [depthSize3]: 0 }',
        '  let throttle = null',
        '  let walkedConstituents = 0',
        '',
        '  // Walk all constituents IN PARALLEL via Promise.all. Sequential walks of 60 constituents',
        '  // exceed the ts-exec step timeout; parallel collapses to max(single-call latency) ~1-2s.',
        '  const constituentsToWalk = constituents.filter((c) => c.yes_token)',
        '  const results = await Promise.all(constituentsToWalk.map(async (c) => {',
        '    try {',
        '      const ob = await callTool("getPredictionOrderbook", {',
        '        tokenId: String(c.yes_token),',
        '        slippageSizes: sizes,',
        '      })',
        '      return { c, ob }',
        '    } catch (e) {',
        '      return { c, ob: null }',
        '    }',
        '  }))',
        '',
        '  for (const { c, ob } of results) {',
        '    if (!ob) continue',
        '    const slip = (ob && ob.slippageEstimates) || []',
        '    for (const s of sizes) {',
        '      const est = slip.find((x) => x.size === s && x.side === side)',
        '      if (!est) continue',
        '      basketSum[s] = (basketSum[s] || 0) + Number(est.avgFillPrice)',
        '    }',
        '    const fillable = slip.filter((x) => x.side === side && x.fullyFillable)',
        '    const maxFillable = fillable.reduce((m, x) => Math.max(m, x.size), 0)',
        '    if (!throttle || maxFillable < throttle.maxFillable) {',
        '      throttle = { slug: c.slug, maxFillable }',
        '    }',
        '    walkedConstituents++',
        '  }',
        '',
        '  function gapBpAt(size) {',
        '    const sum = basketSum[size]',
        '    if (!sum) return 0',
        '    return side === "sell" ? (sum - 1.0) * 10000 : (1.0 - sum) * 10000',
        '  }',
        '',
        '  const gap50 = Math.round(gapBpAt(depthSize1))',
        '  const gap500 = Math.round(gapBpAt(depthSize2))',
        '  const gap5k = Math.round(gapBpAt(depthSize3))',
        '',
        '  const walkComplete = walkedConstituents === ev.n_constituents',
        '  const classified = {',
        '    event_slug: ev.event_slug,',
        '    event_title: ev.event_title,',
        '    direction: ev.direction,',
        '    n_constituents: ev.n_constituents,',
        '    walked_constituents: walkedConstituents,',
        '    walk_complete: walkComplete,',
        '    sum_yes: ev.sum_yes,',
        '    top_of_book_gap_bp: ev.deviation_bp,',
        '    gap_at_50_bp: gap50,',
        '    gap_at_500_bp: gap500,',
        '    gap_at_5000_bp: gap5k,',
        '    throttle,',
        '    ev_vol: ev.ev_vol,',
        '  }',
        '',
        '  // Conservative: incomplete walks classified as marginal even if gaps look real.',
        '  // Incomplete basket sum is downward-biased on sell side and upward-biased on buy side.',
        '  if (gap50 < 0) {',
        '    trap.push(classified)',
        '  } else if (!walkComplete) {',
        '    marginal.push(classified)',
        '  } else if (gap500 < 50) {',
        '    marginal.push(classified)',
        '  } else {',
        '    real.push(classified)',
        '  }',
        '}',
        '',
        'const timestamp = new Date().toISOString()',
        'const result = { timestamp, real, marginal, trap }',
        'await kv.set("negrisk:latest_classified", JSON.stringify(result))',
        'await fs.promises.writeFile(',
        '  "/workspace/scratch/negrisk_classified.json",',
        '  JSON.stringify(result, null, 2)',
        ')',
        '',
        'const lines = []',
        'lines.push("# NegRisk Event Arbitrage Scan")',
        'lines.push("")',
        'lines.push("Timestamp: " + timestamp)',
        'lines.push("Real signals: " + real.length)',
        'lines.push("Marginal signals: " + marginal.length)',
        'lines.push("Traps: " + trap.length)',
        'lines.push("")',
        'if (real.length > 0) {',
        '  lines.push("## Real signals (clear at $500/mkt)")',
        '  for (const r of real) {',
        '    const evVolFmt = "$" + Math.round(r.ev_vol).toLocaleString()',
        '    const thr = r.throttle ? (r.throttle.slug + " (max " + r.throttle.maxFillable + ")") : "n/a"',
        '    lines.push(',
        '      "- **" + r.event_slug + "** (" + r.direction + ", n=" + r.n_constituents + ") | " +',
        '      "top " + r.top_of_book_gap_bp + "bp | $50 " + r.gap_at_50_bp + "bp | $500 " + r.gap_at_500_bp + "bp | $5K " + r.gap_at_5000_bp + "bp | ev_vol " + evVolFmt + " | throttle: " + thr',
        '    )',
        '  }',
        '}',
        'await fs.promises.writeFile("/workspace/scratch/negrisk_summary.md", lines.join("\\n"))',
        '',
        'export default {',
        '  real_count: real.length,',
        '  marginal_count: marginal.length,',
        '  trap_count: trap.length,',
        '  real,',
        '}',
      ].join("\n"),
    },
  ],
})
