import defineWorkflow from "/runtime/tools/workflow/defineWorkflow"

export default defineWorkflow({
  version: 1,
  id: "negrisk-flb-harvest-scanner",
  name: "NegRisk Favourite-Longshot Bias Harvest Scanner",
  description:
    "Scan active Polymarket negRisk events whose constituent YES prices sum to ~1.0 (no mechanical Pack-1 arb), de-vig to risk-neutral implied probabilities, apply a horse-racing power-transform debiasing model (p_true is proportional to q^gamma) under three FLB-strength scenarios, and surface flagship-tier baskets whose overpriced longshot tail clears a fee floor at the MEASURABLE (gamma=1, overround-only) scenario. The behavioural FLB premium (gamma>1) is reported as literature-anchored upside, NOT as the eligibility gate.",
  triggers: [{ manual: true }],
  inputs: [
    { name: "limit", type: "number", required: false, default: 500 },
    { name: "minConstituents", type: "number", required: false, default: 4 },
    { name: "maxAbsDeviation", type: "number", required: false, default: 0.10 },
    { name: "minEventVolumeUsd", type: "number", required: false, default: 1000000 },
    { name: "longshotCeiling", type: "number", required: false, default: 0.05 },
    { name: "longshotFloor", type: "number", required: false, default: 0.01 },
    { name: "minTailConstituents", type: "number", required: false, default: 3 },
    { name: "gammaConservative", type: "number", required: false, default: 1.0 },
    { name: "gammaCentral", type: "number", required: false, default: 1.10 },
    { name: "gammaAggressive", type: "number", required: false, default: 1.20 },
    { name: "feeBufferBp", type: "number", required: false, default: 50 },
    { name: "depthSizeUsd", type: "number", required: false, default: 50 },
    { name: "maxConstituentsToWalk", type: "number", required: false, default: 100 },
    { name: "snapshotPrefix", type: "string", required: false, default: "flb:" },
  ],
  output_mode: "inline",
  steps: [
    {
      id: "fetch_and_register",
      name: "Fetch active Polymarket events and capture the auto-registered SQL table name",
      type: "ts",
      timeout: 60000,
      allow: ["fetchPolymarketData"],
      code: [
        '// Self-bootstrap pattern (identical to Pack 1 surfacer / Pack 2 scanner Step 1).',
        '// fetchPolymarketData via callTool exceeds the ts-exec response budget; via exec to',
        '// host-tools at limit=5 it completes in ~1.6s and auto-registers fetchPolymarketData_<hash>.',
        'try {',
        '  await exec("mkdir -p /workspace/scratch && host-tools fetchPolymarketData \'{\\"dataset\\":\\"events\\",\\"active\\":true,\\"limit\\":5}\' --json-output-only > /workspace/scratch/flb_bootstrap.txt 2>&1")',
        '} catch (e) {',
        '  // sqlite_master discovery will fall back to any pre-existing table.',
        '}',
        '',
        '// Discover the source table from the bootstrap output DIRECTLY. The host tool returns the',
        '// exact registered table name ({"table":"fetchPolymarketData_<hash>"}) even when it reports',
        '// dataset_too_large. We parse that rather than guessing via sqlite_master ROWID ordering:',
        '// ROWID on sqlite_master tracks b-tree page allocation, NOT creation time, so after any',
        '// CREATE/DROP churn (or a stale markets-dataset table from another tool) the "newest by',
        '// ROWID" heuristic can silently select the WRONG dataset and the event grouping returns 0.',
        'let sourceTable = null',
        'try {',
        '  const bootRaw = await fs.promises.readFile("/workspace/scratch/flb_bootstrap.txt", "utf8")',
        '  const m = bootRaw.match(/"table"\\s*:\\s*"(fetchPolymarketData_[a-zA-Z0-9_]+)"/)',
        '  if (m) sourceTable = m[1]',
        '} catch (e) {',
        '  // fall through to sqlite_master discovery below',
        '}',
        'if (!sourceTable) {',
        '  const tableQuery = await sql("SELECT name FROM sqlite_master WHERE type=\'table\' AND name LIKE \'fetchPolymarketData_%\' ORDER BY ROWID DESC LIMIT 1")',
        '  sourceTable = (tableQuery && tableQuery[0] && tableQuery[0].name) || null',
        '}',
        '',
        '// Defense: refuse to interpolate any sourceTable name that does not match the expected',
        '// host-tool pattern, hardening against future drift in table-naming that could expose a',
        '// shell-quote or SQL-injection vector through the exec calls below.',
        'if (sourceTable && !/^fetchPolymarketData_[a-zA-Z0-9_]+$/.test(sourceTable)) {',
        '  sourceTable = null',
        '}',
        '',
        'let tableName',
        'let rowCount = 0',
        'if (sourceTable) {',
        '  // Alias + dedup-by-market_id (host tool appends across calls within a session).',
        '  await exec("sql query \'DROP TABLE IF EXISTS polymarket_flb_raw\'")',
        '  await exec("sql query \'CREATE TABLE polymarket_flb_raw AS SELECT * FROM " + sourceTable + " WHERE rowid IN (SELECT MAX(rowid) FROM " + sourceTable + " GROUP BY market_id)\'")',
        '  const countResult = await sql("SELECT COUNT(*) AS n FROM polymarket_flb_raw")',
        '  rowCount = Number((countResult && countResult[0] && countResult[0].n) || 0)',
        '  tableName = "polymarket_flb_raw"',
        '} else {',
        '  tableName = "polymarket_flb_raw"',
        '  rowCount = 0',
        '}',
        '',
        'const fetchMeta = { table: tableName, fetched: rowCount, timestamp: new Date().toISOString() }',
        'await kv.set("flb:current_table", JSON.stringify(fetchMeta))',
        '',
        'export default fetchMeta',
      ].join("\n"),
    },
    {
      id: "score_flb",
      name: "De-vig each flagship negRisk basket, debias under three gamma scenarios, score the longshot-tail sell edge, depth-walk the tail for tradeability",
      type: "ts",
      depends_on: ["fetch_and_register"],
      timeout: 180000,
      allow: ["getPredictionOrderbook"],
      code: [
        'const minConstituents = 4',
        'const maxAbsDeviation = 0.10',
        'const minEventVolumeUsd = 1000000',
        'const longshotCeiling = 0.05',
        '// Lower bound on the tail: classic FLB is best-supported in the moderate-longshot band.',
        '// The extreme tail (price < longshotFloor) is where the literature is mixed on direction',
        '// (some studies find REVERSE FLB at sub-1% prices) and where a single resolution-source',
        '// surprise dominates. We exclude it rather than bet on a contested sign.',
        'const longshotFloor = 0.01',
        'const minTailConstituents = 3',
        'const gammaConservative = 1.0',
        'const gammaCentral = 1.10',
        'const gammaAggressive = 1.20',
        'const feeBufferBp = 50',
        'const depthSizeUsd = 50',
        'const maxConstituentsToWalk = 100',
        '',
        'const tableMeta = await kv.get("flb:current_table")',
        'const tableMetaParsed = tableMeta ? JSON.parse(tableMeta.value || tableMeta) : null',
        'let tableName = (tableMetaParsed && tableMetaParsed.table) || "polymarket_flb_raw"',
        '// Defense: refuse to interpolate non-conforming table names into SQL.',
        'if (!/^[a-zA-Z0-9_]+$/.test(tableName)) {',
        '  tableName = "polymarket_flb_raw"',
        '}',
        '',
        '// Event-level aggregate: sum_yes (negRisk sanity), constituent count, lifetime volume.',
        '// Sum over priced constituents only (yes_price > 0); dead/placeholder markets at p=0',
        '// contribute nothing and would only dilute the count.',
        'const eventAggSql =',
        '  "SELECT event_slug, MIN(event_title) AS event_title, COUNT(*) AS n, " +',
        '  "ROUND(SUM(CAST(yes_price AS REAL)), 6) AS sum_yes, " +',
        '  "ROUND(SUM(CAST(volume_total_usd AS REAL)), 0) AS ev_vol " +',
        '  "FROM " + tableName + " " +',
        '  "WHERE event_slug IS NOT NULL AND CAST(hours_until_end AS REAL) > 0 AND CAST(yes_price AS REAL) > 0 " +',
        '  "GROUP BY event_slug " +',
        '  "HAVING n >= " + minConstituents',
        'const eventRows = await sql(eventAggSql)',
        '',
        '// Flagship + negRisk-sanity filter. FLB harvest fires when the basket sums to ~1.0',
        '// (so Pack 1 sees NO mechanical arb) but the internal allocation is biased.',
        'const eligibleEvents = (eventRows || []).filter((r) => {',
        '  const sumYes = Number(r.sum_yes)',
        '  if (!Number.isFinite(sumYes)) return false',
        '  if (Math.abs(sumYes - 1.0) > maxAbsDeviation) return false',
        '  if (Number(r.ev_vol || 0) < minEventVolumeUsd) return false',
        '  return true',
        '})',
        'const eligibleEventSlugs = new Set(eligibleEvents.map((e) => e.event_slug))',
        'const eventVolBySlug = {}',
        'const eventTitleBySlug = {}',
        'for (const e of eligibleEvents) {',
        '  eventVolBySlug[e.event_slug] = Number(e.ev_vol || 0)',
        '  eventTitleBySlug[e.event_slug] = e.event_title',
        '}',
        '',
        '// One SQL fetch for all constituents (no per-event WHERE concatenation; no injection vector).',
        'const allConstSql =',
        '  "SELECT event_slug, event_title, slug, question, " +',
        '  "CAST(yes_price AS REAL) AS yes_price, " +',
        '  "CAST(volume_24h_usd AS REAL) AS vol_24h, " +',
        '  "CAST(volume_total_usd AS REAL) AS vol_total, " +',
        '  "SUBSTR(clob_token_ids, 1, INSTR(clob_token_ids, \\",\\") - 1) AS yes_token, " +',
        '  "SUBSTR(clob_token_ids, INSTR(clob_token_ids, \\",\\") + 1) AS no_token " +',
        '  "FROM " + tableName + " " +',
        '  "WHERE CAST(hours_until_end AS REAL) > 0 AND CAST(yes_price AS REAL) > 0"',
        'const allConstituents = await sql(allConstSql)',
        '',
        '// Group live (priced) constituents by event.',
        'const byEvent = {}',
        'for (const c of (allConstituents || [])) {',
        '  if (!c.event_slug || !eligibleEventSlugs.has(c.event_slug)) continue',
        '  const p = Number(c.yes_price)',
        '  if (!Number.isFinite(p) || p <= 0) continue',
        '  if (!byEvent[c.event_slug]) byEvent[c.event_slug] = []',
        '  byEvent[c.event_slug].push(c)',
        '}',
        '',
        '// Horse-racing FLB debiasing: p_true_i = q_i^gamma / sum_j(q_j^gamma).',
        '// gamma=1 => no behavioural bias (p_true == de-vigged q; edge is the overround only).',
        '// gamma>1 => mass shifts toward favourites, away from longshots (classic FLB).',
        'function debias(qs, gamma) {',
        '  const pw = qs.map((q) => Math.pow(q, gamma))',
        '  const z = pw.reduce((a, b) => a + b, 0)',
        '  if (!(z > 0)) return qs.map(() => 0)',
        '  return pw.map((v) => v / z)',
        '}',
        '',
        'const baskets = []',
        'for (const slug of Object.keys(byEvent)) {',
        '  const cons = byEvent[slug]',
        '  const prices = cons.map((c) => Number(c.yes_price))',
        '  const sumLive = prices.reduce((a, b) => a + b, 0)',
        '  if (!(sumLive > 0)) continue',
        '  const q = prices.map((p) => p / sumLive)',
        '  const ptC = debias(q, gammaConservative)',
        '  const ptM = debias(q, gammaCentral)',
        '  const ptA = debias(q, gammaAggressive)',
        '',
        '  // Tail = constituents at or below the longshot ceiling (the overpriced names we sell).',
        '  const tail = []',
        '  for (let i = 0; i < cons.length; i++) {',
        '    if (prices[i] > longshotCeiling) continue',
        '    if (prices[i] < longshotFloor) continue',
        '    tail.push({',
        '      event_slug: slug,',
        '      event_title: eventTitleBySlug[slug] || cons[i].event_title,',
        '      slug: cons[i].slug,',
        '      question: cons[i].question,',
        '      yes_token: cons[i].yes_token,',
        '      // Shorting the overpriced longshot YES is mechanically a BUY of the NO token.',
        '      // Collateral required for the short ~= no_price ~= (1 - yes_price), so the short',
        '      // ties up near-full collateral per share. The executor buys NO; ROC accounts for this.',
        '      no_token: cons[i].no_token,',
        '      yes_price: Number(prices[i].toFixed(6)),',
        '      no_collateral_per_share: Number((1 - prices[i]).toFixed(6)),',
        '      q: Number(q[i].toFixed(6)),',
        '      p_true_conservative: Number(ptC[i].toFixed(6)),',
        '      p_true_central: Number(ptM[i].toFixed(6)),',
        '      p_true_aggressive: Number(ptA[i].toFixed(6)),',
        '      // sell-YES edge per share = market price - true prob (positive => overpriced => sell).',
        '      sell_edge_conservative: Number((prices[i] - ptC[i]).toFixed(6)),',
        '      sell_edge_central: Number((prices[i] - ptM[i]).toFixed(6)),',
        '      sell_edge_aggressive: Number((prices[i] - ptA[i]).toFixed(6)),',
        '    })',
        '  }',
        '  if (tail.length < minTailConstituents) continue',
        '',
        '  const tailSellNotionalPerShare = tail.reduce((s, t) => s + t.yes_price, 0)',
        '  if (!(tailSellNotionalPerShare > 0)) continue',
        '  // Capital actually deployed to short the tail = sum of NO-collateral (~ 1 - yes_price each).',
        '  // This is the HONEST denominator for return-on-capital: each short ties up ~$1/share.',
        '  const tailCollateralPerShare = tail.reduce((s, t) => s + t.no_collateral_per_share, 0)',
        '  const sumEdge = (key) => tail.reduce((s, t) => s + t[key], 0)',
        '  const edgeC = sumEdge("sell_edge_conservative")',
        '  const edgeM = sumEdge("sell_edge_central")',
        '  const edgeA = sumEdge("sell_edge_aggressive")',
        '  const tailWinProbCentral = tail.reduce((s, t) => s + t.p_true_central, 0)',
        '  const tailWinProbConservative = tail.reduce((s, t) => s + t.p_true_conservative, 0)',
        '',
        '  baskets.push({',
        '    event_slug: slug,',
        '    event_title: eventTitleBySlug[slug] || "",',
        '    ev_vol: eventVolBySlug[slug] || 0,',
        '    n_live_constituents: cons.length,',
        '    sum_yes_live: Number(sumLive.toFixed(6)),',
        '    overround_pct: Number(((sumLive - 1) * 100).toFixed(3)),',
        '    n_tail: tail.length,',
        '    tail_sell_notional_per_share_usd: Number(tailSellNotionalPerShare.toFixed(6)),',
        '    tail_collateral_per_share_usd: Number(tailCollateralPerShare.toFixed(6)),',
        '    // Edge as % of shorted notional (flatters the strategy — small denominator).',
        '    // Conservative (gamma=1) is algebraically just overround/(1+overround); it is NOT a',
        '    // distinctively-FLB edge (every constituent shares it) — it is maker-spread capture.',
        '    tail_edge_pct_conservative: Number((100 * edgeC / tailSellNotionalPerShare).toFixed(3)),',
        '    tail_edge_pct_central: Number((100 * edgeM / tailSellNotionalPerShare).toFixed(3)),',
        '    tail_edge_pct_aggressive: Number((100 * edgeA / tailSellNotionalPerShare).toFixed(3)),',
        '    // Edge as % of COLLATERAL DEPLOYED (the honest return-on-capital denominator).',
        '    // This is the number to judge the strategy by; it is much smaller than edge-on-notional',
        '    // because shorting a longshot ties up ~full collateral per share. NOT annualised here',
        '    // (holding period runs to event resolution — see PROFITABILITY_ANALYSIS_FLB.md).',
        '    tail_roc_pct_conservative: Number((100 * edgeC / tailCollateralPerShare).toFixed(4)),',
        '    tail_roc_pct_central: Number((100 * edgeM / tailCollateralPerShare).toFixed(4)),',
        '    tail_roc_pct_aggressive: Number((100 * edgeA / tailCollateralPerShare).toFixed(4)),',
        '    tail_collective_win_prob_conservative: Number(tailWinProbConservative.toFixed(5)),',
        '    tail_collective_win_prob_central: Number(tailWinProbCentral.toFixed(5)),',
        '    tail_constituents: tail,',
        '  })',
        '}',
        '',
        '// Depth-walk the tail constituents of candidate baskets to confirm a live, non-degenerate',
        '// orderbook exists (we cannot post a maker sell on a dead book) and record bestBid/bestAsk',
        '// + the sell-side executable size for the executor. Bounded by maxConstituentsToWalk.',
        'const walkList = []',
        'for (const b of baskets) {',
        '  for (const t of b.tail_constituents) {',
        '    if (walkList.length >= maxConstituentsToWalk) break',
        '    if (t.yes_token) walkList.push(t)',
        '  }',
        '}',
        'const obResults = await Promise.all(walkList.map(async (t) => {',
        '  try {',
        '    const ob = await callTool("getPredictionOrderbook", { tokenId: String(t.yes_token), slippageSizes: [depthSizeUsd] })',
        '    return { token: t.yes_token, ob }',
        '  } catch (e) {',
        '    return { token: t.yes_token, ob: null }',
        '  }',
        '}))',
        'const obByToken = {}',
        'for (const r of obResults) { obByToken[r.token] = r.ob }',
        '',
        'for (const b of baskets) {',
        '  let tradeable = 0',
        '  for (const t of b.tail_constituents) {',
        '    const ob = obByToken[t.yes_token]',
        '    const summary = (ob && ob.summary) || {}',
        '    const bestBid = Number(summary.bestBid || 0)',
        '    const bestAsk = Number(summary.bestAsk || 0)',
        '    const slip = (ob && ob.slippageEstimates) || []',
        '    const sellEst = slip.find((x) => x.size === depthSizeUsd && x.side === "sell")',
        '    t.best_bid = Number.isFinite(bestBid) ? bestBid : 0',
        '    t.best_ask = Number.isFinite(bestAsk) ? bestAsk : 0',
        '    t.sell_avg_fill_50 = sellEst ? Number(sellEst.avgFillPrice) : 0',
        '    t.sell_fully_fillable_50 = !!(sellEst && sellEst.fullyFillable)',
        '    // Tradeable = live two-sided book. A degenerate book (no bid, crossed, or zero) is excluded.',
        '    t.tradeable = Number.isFinite(t.best_bid) && Number.isFinite(t.best_ask) && t.best_bid > 0 && t.best_ask > t.best_bid',
        '    if (t.tradeable) tradeable++',
        '  }',
        '  b.n_tail_tradeable = tradeable',
        '  // Eligibility gate: the MEASURABLE (gamma=1, overround-only) tail edge must clear the fee',
        '  // buffer AND at least minTailConstituents tail names must have a live book. The behavioural',
        '  // FLB upside (central/aggressive gamma) is reported but is NOT the gate.',
        '  b.eligible = (b.tail_edge_pct_conservative > (feeBufferBp / 100)) && (tradeable >= minTailConstituents)',
        '}',
        '',
        'baskets.sort((a, b) => b.tail_edge_pct_conservative - a.tail_edge_pct_conservative)',
        'await fs.promises.writeFile("/workspace/scratch/flb_scored.json", JSON.stringify(baskets, null, 2))',
        '',
        'export default {',
        '  scoredBaskets: baskets.length,',
        '  eligibleBaskets: baskets.filter((b) => b.eligible).length,',
        '  top: baskets.slice(0, 5).map((b) => ({',
        '    event_slug: b.event_slug,',
        '    overround_pct: b.overround_pct,',
        '    n_tail_tradeable: b.n_tail_tradeable,',
        '    edge_pct_floor: b.tail_edge_pct_conservative,',
        '    edge_pct_central: b.tail_edge_pct_central,',
        '    eligible: b.eligible,',
        '  })),',
        '}',
      ].join("\n"),
    },
    {
      id: "surface",
      name: "Filter to eligible baskets and persist the longshot-tail-short candidate set to KV for the executor",
      type: "ts",
      depends_on: ["score_flb"],
      timeout: 30000,
      code: [
        'const raw = await fs.promises.readFile("/workspace/scratch/flb_scored.json", "utf8").catch(() => "[]")',
        'const baskets = JSON.parse(raw)',
        'const eligible = baskets.filter((b) => b.eligible)',
        '',
        '// Flatten eligible tail constituents into a per-name short list the executor consumes,',
        '// keeping only tradeable names and tagging each with its parent event for diversification caps.',
        'const shortList = []',
        'for (const b of eligible) {',
        '  for (const t of b.tail_constituents) {',
        '    if (!t.tradeable) continue',
        '    shortList.push({',
        '      event_slug: b.event_slug,',
        '      event_title: b.event_title,',
        '      slug: t.slug,',
        '      yes_token: t.yes_token,',
        '      no_token: t.no_token,',
        '      yes_price: t.yes_price,',
        '      no_collateral_per_share: t.no_collateral_per_share,',
        '      best_bid: t.best_bid,',
        '      best_ask: t.best_ask,',
        '      p_true_central: t.p_true_central,',
        '      p_true_conservative: t.p_true_conservative,',
        '      sell_edge_conservative: t.sell_edge_conservative,',
        '      sell_edge_central: t.sell_edge_central,',
        '      sell_edge_aggressive: t.sell_edge_aggressive,',
        '    })',
        '  }',
        '}',
        '// Sort by descending CONSERVATIVE (measurable) per-share edge so the executor fills',
        '// the most-defensibly-overpriced names first within its caps.',
        'shortList.sort((a, b) => b.sell_edge_conservative - a.sell_edge_conservative)',
        '',
        'const timestamp = new Date().toISOString()',
        'const payload = {',
        '  timestamp,',
        '  eligible_baskets: eligible.map((b) => ({',
        '    event_slug: b.event_slug,',
        '    event_title: b.event_title,',
        '    overround_pct: b.overround_pct,',
        '    n_tail_tradeable: b.n_tail_tradeable,',
        '    tail_sell_notional_per_share_usd: b.tail_sell_notional_per_share_usd,',
        '    tail_edge_pct_conservative: b.tail_edge_pct_conservative,',
        '    tail_edge_pct_central: b.tail_edge_pct_central,',
        '    tail_edge_pct_aggressive: b.tail_edge_pct_aggressive,',
        '    tail_collective_win_prob_central: b.tail_collective_win_prob_central,',
        '  })),',
        '  short_candidates: shortList,',
        '  total_eligible_baskets: eligible.length,',
        '  total_short_candidates: shortList.length,',
        '}',
        'await kv.set("flb:eligible_baskets", JSON.stringify(payload))',
        'const hourKey = "flb:" + timestamp.slice(0, 13)',
        'await kv.set(hourKey, JSON.stringify(payload))',
        'await fs.promises.writeFile("/workspace/scratch/flb_eligible.json", JSON.stringify(payload, null, 2))',
        '',
        'const lines = []',
        'lines.push("# NegRisk FLB Harvest — Eligibility Scan")',
        'lines.push("")',
        'lines.push("Timestamp: " + timestamp)',
        'lines.push("Eligible baskets: " + eligible.length + " | short candidates: " + shortList.length)',
        'lines.push("")',
        'lines.push("Edge is reported at three FLB-strength scenarios. ONLY the conservative (gamma=1,")',
        'lines.push("overround-only) column is venue-measurable and gates eligibility; central/aggressive")',
        'lines.push("are literature-anchored behavioural-bias upside and are NOT verified on this venue.")',
        'if (eligible.length > 0) {',
        '  lines.push("")',
        '  lines.push("## Eligible baskets (sorted by measurable floor edge)")',
        '  for (const b of eligible) {',
        '    lines.push(',
        '      "- **" + b.event_slug + "** | overround " + b.overround_pct + "% | tail tradeable " + b.n_tail_tradeable +',
        '      " | edge floor " + b.tail_edge_pct_conservative + "% / central " + b.tail_edge_pct_central + "% / aggr " + b.tail_edge_pct_aggressive + "%" +',
        '      " | tail win-prob(central) " + (b.tail_collective_win_prob_central * 100).toFixed(1) + "%"',
        '    )',
        '  }',
        '}',
        'await fs.promises.writeFile("/workspace/scratch/flb_eligibility.md", lines.join("\\n"))',
        '',
        'export default {',
        '  total_eligible_baskets: eligible.length,',
        '  total_short_candidates: shortList.length,',
        '  top_baskets: payload.eligible_baskets.slice(0, 3),',
        '}',
      ].join("\n"),
    },
  ],
})
